export const oneRoom = [
  {
    name: '1014',
    balcony: true,
    studio: false,
    oneRoom: true,
    twoRoom: false,
    threeRoom: false,
    squareMeters: '58',
    view: 'Море',
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '5',
    wifi: true,
    coffeeMachine: true,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [],
    summerPrice: '15 000',
    winterPrice: '12 000',
    description: '',
  },
  {
    name: '1013',
    balcony: true,
    studio: false,
    oneRoom: true,
    twoRoom: false,
    threeRoom: false,
    squareMeters: '58',
    view: 'Море',
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '5',
    wifi: true,
    coffeeMachine: true,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [],
    summerPrice: '15 000',
    winterPrice: '12 000',
    description: '',
  },
  {
    name: '416',
    balcony: true,
    studio: false,
    oneRoom: true,
    twoRoom: false,
    threeRoom: false,
    squareMeters: '45',
    view: 'Город',
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [],
    summerPrice: '15 000',
    winterPrice: '12 000',
    description: '',
  },
  {
    name: '312',
    balcony: true,
    studio: false,
    oneRoom: true,
    twoRoom: false,
    threeRoom: false,
    squareMeters: '45',
    view: 'Город',
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [],
    summerPrice: '15 000',
    winterPrice: '12 000',
    description: '',
  },
  {
    name: '310',
    balcony: false,
    studio: false,
    oneRoom: true,
    twoRoom: false,
    threeRoom: false,
    squareMeters: '45',
    view: 'Город',
    hairDryer: true,
    dishwasher: false,
    oven: true,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [],
    summerPrice: '15 000',
    winterPrice: '12 000',
    description: '',
  },
];
