export const studio = [
  {
    name: '1303',
    balcony: true,
    studio: true,
    oneRoom: false,
    twoRoom: false,
    threeRoom: false,
    squareMeters: '52',
    view: 'Море',
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: true,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [],
    summerPrice: '15 000',
    winterPrice: '12 000',
    description: '',
  },
  {
    name: '1207',
    balcony: true,
    studio: true,
    oneRoom: false,
    twoRoom: false,
    threeRoom: false,
    squareMeters: '57',
    view: 'Море',
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [],
    summerPrice: '15 000',
    winterPrice: '12 000',
    description: '',
  },
  {
    name: '705',
    balcony: true,
    studio: true,
    oneRoom: false,
    twoRoom: false,
    threeRoom: false,
    squareMeters: '53',
    view: 'Море',
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [],
    summerPrice: '15 000',
    winterPrice: '12 000',
    description: '',
  },
  {
    name: '605',
    balcony: true,
    studio: true,
    oneRoom: false,
    twoRoom: false,
    threeRoom: false,
    squareMeters: '50',
    view: 'Город',
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [],
    summerPrice: '15 000',
    winterPrice: '12 000',
    description: '',
  },
];
