export const threeRoom = [
  {
    name: '1416',
    balcony: false,
    studio: false,
    oneRoom: false,
    twoRoom: false,
    threeRoom: true,
    squareMeters: '60',
    view: 'Море',
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '6',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [],
    summerPrice: '15 000',
    winterPrice: '12 000',
    description: '',
  },
  {
    name: '1415',
    balcony: false,
    studio: false,
    oneRoom: false,
    twoRoom: false,
    threeRoom: true,
    squareMeters: '60',
    view: 'Море',
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '6',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [],
    summerPrice: '15 000',
    winterPrice: '12 000',
    description: '',
  },
  {
    name: '1313',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: false,
    threeRoom: true,
    squareMeters: '58',
    view: 'Море',
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '6',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [],
    summerPrice: '15 000',
    winterPrice: '12 000',
    description: '',
  },
  {
    name: '1304',
    balcony: false,
    studio: false,
    oneRoom: false,
    twoRoom: false,
    threeRoom: true,
    squareMeters: '0',
    view: 'Город',
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '1',
    wifi: true,
    coffeeMachine: true,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [],
    summerPrice: '15 000',
    winterPrice: '12 000',
    description: '',
  },
  {
    name: '1110',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: false,
    threeRoom: true,
    squareMeters: '57',
    view: 'Море',
    hairDryer: true,
    dishwasher: true,
    oven: false,
    sleepingPlaces: '6',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [],
    summerPrice: '15 000',
    winterPrice: '12 000',
    description: '',
  },
  {
    name: '402',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: false,
    threeRoom: true,
    squareMeters: '57',
    view: 'Город',
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '6',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [],
    summerPrice: '15 000',
    winterPrice: '12 000',
    description: '',
  },
  {
    name: '218',
    balcony: false,
    studio: false,
    oneRoom: false,
    twoRoom: false,
    threeRoom: true,
    squareMeters: '48',
    view: 'Город',
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '6',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [],
    summerPrice: '15 000',
    winterPrice: '12 000',
    description: '',
  },
];
