export const twoRoom = [
  {
    name: '1410',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '54',
    view: 'Море',
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: true,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [],
    summerPrice: '15 000',
    winterPrice: '12 000',
    description: '',
  },
  {
    name: '1409',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '50',
    view: 'Море',
    hairDryer: true,
    dishwasher: false,
    oven: true,
    sleepingPlaces: '3',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [],
    summerPrice: '15 000',
    winterPrice: '12 000',
    description: '',
  },
  {
    name: '1404',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '50',
    view: 'Море',
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [],
    summerPrice: '15 000',
    winterPrice: '12 000',
    description: '',
  },
  {
    name: '1208',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '57',
    view: 'Море',
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [],
    summerPrice: '15 000',
    winterPrice: '12 000',
    description: '',
  },
  {
    name: '1206',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '57',
    view: 'Море',
    hairDryer: true,
    dishwasher: true,
    oven: false,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [],
    summerPrice: '15 000',
    winterPrice: '12 000',
    description: '',
  },
  {
    name: '1111',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '58',
    view: 'Море',
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [],
    summerPrice: '15 000',
    winterPrice: '12 000',
    description: '',
  },
  {
    name: '1109',
    balcony: false,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '56',
    view: 'Море',
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: true,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [],
    summerPrice: '15 000',
    winterPrice: '12 000',
    description: '',
  },
  {
    name: '1105',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '57',
    view: 'Море',
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '6',
    wifi: true,
    coffeeMachine: true,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [],
    summerPrice: '15 000',
    winterPrice: '12 000',
    description: '',
  },
  {
    name: '1104',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '57',
    view: 'Море',
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '6',
    wifi: true,
    coffeeMachine: true,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [],
    summerPrice: '15 000',
    winterPrice: '12 000',
    description: '',
  },
  {
    name: '1103',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '57',
    view: 'Море',
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '5',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [],
    summerPrice: '15 000',
    winterPrice: '12 000',
    description: '',
  },
  {
    name: '1003',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '57',
    view: 'Море',
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [],
    summerPrice: '15 000',
    winterPrice: '12 000',
    description: '',
  },
  {
    name: '907',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '57',
    view: 'Море',
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [],
    summerPrice: '15 000',
    winterPrice: '12 000',
    description: '',
  },
  {
    name: '805',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '57',
    view: 'Море',
    hairDryer: true,
    dishwasher: true,
    oven: false,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [],
    summerPrice: '15 000',
    winterPrice: '12 000',
    description: '',
  },
  {
    name: '716',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '57',
    view: 'Море',
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [],
    summerPrice: '15 000',
    winterPrice: '12 000',
    description: '',
  },
  {
    name: '715',
    balcony: false,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '57',
    view: 'Море',
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [],
    summerPrice: '15 000',
    winterPrice: '12 000',
    description: '',
  },
  {
    name: '712',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '57',
    view: 'Море',
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [],
    summerPrice: '15 000',
    winterPrice: '12 000',
    description: '',
  },
  {
    name: '709',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '54',
    view: 'Море',
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [],
    summerPrice: '15 000',
    winterPrice: '12 000',
    description: '',
  },
  {
    name: '613',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '55',
    view: 'Город',
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: true,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [],
    summerPrice: '15 000',
    winterPrice: '12 000',
    description: '',
  },
  {
    name: '612',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '55',
    view: 'Город',
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '5',
    wifi: true,
    coffeeMachine: true,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [],
    summerPrice: '15 000',
    winterPrice: '12 000',
    description: '',
  },
  {
    name: '607',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '53',
    view: 'Город',
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: true,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [],
    summerPrice: '15 000',
    winterPrice: '12 000',
    description: '',
  },
  {
    name: '606',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '53',
    view: 'Город',
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [],
    summerPrice: '15 000',
    winterPrice: '12 000',
    description: '',
  },
  {
    name: '509',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '57',
    view: 'Город',
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '5',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [],
    summerPrice: '15 000',
    winterPrice: '12 000',
    description: '',
  },
  {
    name: '503',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '52',
    view: 'Город',
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [],
    summerPrice: '15 000',
    winterPrice: '12 000',
    description: '',
  },
  {
    name: '415',
    balcony: false,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '45',
    view: 'Город',
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [],
    summerPrice: '15 000',
    winterPrice: '12 000',
    description: '',
  },
  {
    name: '216',
    balcony: false,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '48',
    view: 'Город',
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [],
    summerPrice: '15 000',
    winterPrice: '12 000',
    description: '',
  },
];
