export const table = [
  {
    name: '1416',
    balcony: false,
    studio: false,
    oneRoom: false,
    twoRoom: false,
    threeRoom: true,
    squareMeters: '60',
    view: true,
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '6',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartments/1416/1.jpg',
      '/assets/apartments/1416/2.jpg',
      '/assets/apartments/1416/3.jpg',
      '/assets/apartments/1416/4.jpg',
      '/assets/apartments/1416/5.jpg',
      '/assets/apartments/1416/6.jpg',
      '/assets/apartments/1416/7.jpg',
      '/assets/apartments/1416/8.jpg',
    ],
    summerPrice: '12 000',
    winterPrice: '6 000',
    rooms: '3',
    floor: '14',
    description: '',
    sort: '42',
  },
  {
    name: '1415',
    balcony: false,
    studio: false,
    oneRoom: false,
    twoRoom: false,
    threeRoom: true,
    squareMeters: '60',
    view: true,
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '6',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartments/1415/1.jpg',
      '/assets/apartments/1415/2.jpg',
      '/assets/apartments/1415/3.jpg',
      '/assets/apartments/1415/4.jpg',
      '/assets/apartments/1415/5.jpg',
      '/assets/apartments/1415/6.jpg',
      '/assets/apartments/1415/7.jpg',
      '/assets/apartments/1415/8.jpg',
    ],
    summerPrice: '12 000',
    winterPrice: '6 000',
    rooms: '3',
    floor: '14',
    description: '',
    sort: '41',
  },
  {
    name: '1410',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '54',
    view: true,
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: true,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartments/1410/1.jpg',
      '/assets/apartments/1410/2.jpg',
      '/assets/apartments/1410/3.jpg',
      '/assets/apartments/1410/4.jpg',
      '/assets/apartments/1410/5.jpg',
      '/assets/apartments/1410/6.jpg',
      '/assets/apartments/1410/7.jpg',
      '/assets/apartments/1410/8.jpg',
    ],
    summerPrice: '12 000',
    winterPrice: '6 000',
    rooms: '2',
    floor: '14',
    description: '',
    sort: '40',
  },
  {
    name: '1409',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '50',
    view: true,
    hairDryer: true,
    dishwasher: false,
    oven: true,
    sleepingPlaces: '3',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartments/1409/1.jpg',
      '/assets/apartments/1409/2.jpg',
      '/assets/apartments/1409/3.jpg',
      '/assets/apartments/1409/4.jpg',
      '/assets/apartments/1409/5.jpg',
      '/assets/apartments/1409/6.jpg',
      '/assets/apartments/1409/7.jpg',
      '/assets/apartments/1409/8.jpg',
    ],
    summerPrice: '12 000',
    winterPrice: '6 000',
    rooms: '2',
    floor: '14',
    description: '',
    sort: '39',
  },
  {
    name: '1404',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '50',
    view: true,
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartments/1404/1.jpg',
      '/assets/apartments/1404/2.jpg',
      '/assets/apartments/1404/3.jpg',
      '/assets/apartments/1404/4.jpg',
      '/assets/apartments/1404/5.jpg',
      '/assets/apartments/1404/6.jpg',
      '/assets/apartments/1404/7.jpg',
      '/assets/apartments/1404/8.jpg',
    ],
    summerPrice: '15 000',
    winterPrice: '6 000',
    rooms: '2',
    floor: '14',
    description: '',
    sort: '38',
  },
  {
    name: '1313',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: false,
    threeRoom: true,
    squareMeters: '58',
    view: true,
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '6',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartments/1313/1.jpg',
      '/assets/apartments/1313/2.jpg',
      '/assets/apartments/1313/3.jpg',
      '/assets/apartments/1313/4.jpg',
      '/assets/apartments/1313/5.jpg',
      '/assets/apartments/1313/6.jpg',
      '/assets/apartments/1313/7.jpg',
      '/assets/apartments/1313/8.jpg',
    ],
    summerPrice: '12 500',
    winterPrice: '7 000',
    rooms: '3',
    floor: '13',
    description: '',
    sort: '37',
  },
  {
    name: '1305',
    balcony: false,
    studio: false,
    oneRoom: false,
    twoRoom: false,
    threeRoom: true,
    squareMeters: '59',
    view: false,
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '1',
    wifi: true,
    coffeeMachine: true,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartments/1304 - 1305/1.jpg',
      '/assets/apartments/1304 - 1305/2.jpg',
      '/assets/apartments/1304 - 1305/3.jpg',
      '/assets/apartments/1304 - 1305/4.jpg',
      '/assets/apartments/1304 - 1305/5.jpg',
      '/assets/apartments/1304 - 1305/6.jpg',
      '/assets/apartments/1304 - 1305/7.jpg',
      '/assets/apartments/1304 - 1305/8.jpg',
    ],
    summerPrice: '12 000',
    winterPrice: '6 000',
    rooms: '3',
    floor: '13',
    description: '',
    sort: '36',
  },
  {
    name: '1304',
    balcony: false,
    studio: false,
    oneRoom: false,
    twoRoom: false,
    threeRoom: true,
    squareMeters: '59',
    view: false,
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '1',
    wifi: true,
    coffeeMachine: true,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartments/1304 - 1305/1.jpg',
      '/assets/apartments/1304 - 1305/2.jpg',
      '/assets/apartments/1304 - 1305/3.jpg',
      '/assets/apartments/1304 - 1305/4.jpg',
      '/assets/apartments/1304 - 1305/5.jpg',
      '/assets/apartments/1304 - 1305/6.jpg',
      '/assets/apartments/1304 - 1305/7.jpg',
      '/assets/apartments/1304 - 1305/8.jpg',
    ],
    summerPrice: '12 000',
    winterPrice: '6 000',
    rooms: '3',
    floor: '13',
    description: '',
    sort: '35',
  },
  {
    name: '1303',
    balcony: true,
    studio: true,
    oneRoom: false,
    twoRoom: false,
    threeRoom: false,
    squareMeters: '52',
    view: true,
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: true,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartments/310/1.jpg',
      '/assets/apartments/310/2.jpg',
      '/assets/apartments/310/3.jpg',
      '/assets/apartments/310/4.jpg',
      '/assets/apartments/310/5.jpg',
      '/assets/apartments/310/6.jpg',
      '/assets/apartments/310/7.jpg',
      '/assets/apartments/310/8.jpg',
    ],
    summerPrice: '12 000',
    winterPrice: '6 000',
    rooms: 'Студия',
    floor: '13',
    description: '',
    sort: '34',
  },
  {
    name: '1208',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '57',
    view: true,
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartments/1208/1.jpg',
      '/assets/apartments/1208/2.jpg',
      '/assets/apartments/1208/3.jpg',
      '/assets/apartments/1208/4.jpg',
      '/assets/apartments/1208/5.jpg',
      '/assets/apartments/1208/6.jpg',
      '/assets/apartments/1208/7.jpg',
      '/assets/apartments/1208/8.jpg',
    ],
    summerPrice: '12 000',
    winterPrice: '7 000',
    rooms: '2',
    floor: '12',
    description: '',
    sort: '33',
  },
  {
    name: '1207',
    balcony: true,
    studio: true,
    oneRoom: false,
    twoRoom: false,
    threeRoom: false,
    squareMeters: '57',
    view: true,
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartments/1207/1.jpg',
      '/assets/apartments/1207/2.jpg',
      '/assets/apartments/1207/3.jpg',
      '/assets/apartments/1207/4.jpg',
      '/assets/apartments/1207/5.jpg',
      '/assets/apartments/1207/6.jpg',
      '/assets/apartments/1207/7.jpg',
      '/assets/apartments/1207/8.jpg',
    ],
    summerPrice: '10 000',
    winterPrice: '6 000',
    rooms: 'Студия',
    floor: '12',
    description: '',
    sort: '32',
  },
  {
    name: '1206',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '57',
    view: true,
    hairDryer: true,
    dishwasher: true,
    oven: false,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartments/1206/1.jpg',
      '/assets/apartments/1206/2.jpg',
      '/assets/apartments/1206/3.jpg',
      '/assets/apartments/1206/4.jpg',
      '/assets/apartments/1206/5.jpg',
      '/assets/apartments/1206/6.jpg',
      '/assets/apartments/1206/7.jpg',
      '/assets/apartments/1206/8.jpg',
    ],
    summerPrice: '11 000',
    winterPrice: '6 000',
    rooms: '2',
    floor: '12',
    description: '',
    sort: '31',
  },
  {
    name: '1111',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '58',
    view: true,
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartments/1111/1.jpg',
      '/assets/apartments/1111/2.jpg',
      '/assets/apartments/1111/3.jpg',
      '/assets/apartments/1111/4.jpg',
      '/assets/apartments/1111/5.jpg',
      '/assets/apartments/1111/6.jpg',
      '/assets/apartments/1111/7.jpg',
      '/assets/apartments/1111/8.jpg',
    ],
    summerPrice: '11 000',
    winterPrice: '5 500',
    rooms: '2',
    floor: '11',
    description: '',
    sort: '30',
  },
  {
    name: '1110',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: false,
    threeRoom: true,
    squareMeters: '57',
    view: true,
    hairDryer: true,
    dishwasher: true,
    oven: false,
    sleepingPlaces: '6',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartments/1110/1.jpg',
      '/assets/apartments/1110/2.jpg',
      '/assets/apartments/1110/3.jpg',
      '/assets/apartments/1110/4.jpg',
      '/assets/apartments/1110/5.jpg',
      '/assets/apartments/1110/6.jpg',
      '/assets/apartments/1110/7.jpg',
      '/assets/apartments/1110/8.jpg',
    ],
    summerPrice: '12 000',
    winterPrice: '6 000',
    rooms: '3',
    floor: '11',
    description: '',
    sort: '29',
  },
  {
    name: '1109',
    balcony: false,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '56',
    view: true,
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: true,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartments/1109/1.jpg',
      '/assets/apartments/1109/2.jpg',
      '/assets/apartments/1109/3.jpg',
      '/assets/apartments/1109/4.jpg',
      '/assets/apartments/1109/5.jpg',
      '/assets/apartments/1109/6.jpg',
      '/assets/apartments/1109/7.jpg',
      '/assets/apartments/1109/8.jpg',
    ],
    summerPrice: '10 000',
    winterPrice: '5 000',
    rooms: '2',
    floor: '11',
    description: '',
    sort: '28',
  },
  {
    name: '1105',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '57',
    view: true,
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '6',
    wifi: true,
    coffeeMachine: true,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartments/1104 - 1105/1.jpg',
      '/assets/apartments/1104 - 1105/2.jpg',
      '/assets/apartments/1104 - 1105/3.jpg',
      '/assets/apartments/1104 - 1105/4.jpg',
      '/assets/apartments/1104 - 1105/5.jpg',
      '/assets/apartments/1104 - 1105/6.jpg',
      '/assets/apartments/1104 - 1105/7.jpg',
      '/assets/apartments/1104 - 1105/8.jpg',
    ],
    summerPrice: '12 000',
    winterPrice: '6 000',
    rooms: '2',
    floor: '11',
    description: '',
    sort: '27',
  },
  {
    name: '1104',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '57',
    view: true,
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '6',
    wifi: true,
    coffeeMachine: true,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartments/1104 - 1105/1.jpg',
      '/assets/apartments/1104 - 1105/2.jpg',
      '/assets/apartments/1104 - 1105/3.jpg',
      '/assets/apartments/1104 - 1105/4.jpg',
      '/assets/apartments/1104 - 1105/5.jpg',
      '/assets/apartments/1104 - 1105/6.jpg',
      '/assets/apartments/1104 - 1105/7.jpg',
      '/assets/apartments/1104 - 1105/8.jpg',
    ],
    summerPrice: '12 000',
    winterPrice: '6 000',
    rooms: '2',
    floor: '11',
    description: '',
    sort: '26',
  },
  {
    name: '1103',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '57',
    view: true,
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '5',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartments/1103/1.jpg',
      '/assets/apartments/1103/2.jpg',
      '/assets/apartments/1103/3.jpg',
      '/assets/apartments/1103/4.jpg',
      '/assets/apartments/1103/5.jpg',
      '/assets/apartments/1103/6.jpg',
      '/assets/apartments/1103/7.jpg',
      '/assets/apartments/1103/8.jpg',
    ],
    summerPrice: '10 000',
    winterPrice: '5 000',
    rooms: '2',
    floor: '11',
    description: '',
    sort: '25',
  },
  {
    name: '1014',
    balcony: true,
    studio: false,
    oneRoom: true,
    twoRoom: false,
    threeRoom: false,
    squareMeters: '58',
    view: true,
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '5',
    wifi: true,
    coffeeMachine: true,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartments/1013 - 1014/1.jpg',
      '/assets/apartments/1013 - 1014/2.jpg',
      '/assets/apartments/1013 - 1014/3.jpg',
      '/assets/apartments/1013 - 1014/4.jpg',
      '/assets/apartments/1013 - 1014/5.jpg',
      '/assets/apartments/1013 - 1014/6.jpg',
      '/assets/apartments/1013 - 1014/7.jpg',
      '/assets/apartments/1013 - 1014/8.jpg',
    ],
    summerPrice: '12 000',
    winterPrice: '7 000',
    rooms: '1',
    floor: '10',
    description: '',
    sort: '24',
  },
  {
    name: '1013',
    balcony: true,
    studio: false,
    oneRoom: true,
    twoRoom: false,
    threeRoom: false,
    squareMeters: '58',
    view: true,
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '5',
    wifi: true,
    coffeeMachine: true,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartments/1013 - 1014/1.jpg',
      '/assets/apartments/1013 - 1014/2.jpg',
      '/assets/apartments/1013 - 1014/3.jpg',
      '/assets/apartments/1013 - 1014/4.jpg',
      '/assets/apartments/1013 - 1014/5.jpg',
      '/assets/apartments/1013 - 1014/6.jpg',
      '/assets/apartments/1013 - 1014/7.jpg',
      '/assets/apartments/1013 - 1014/8.jpg',
    ],
    summerPrice: '12 000',
    winterPrice: '7 000',
    rooms: '1',
    floor: '10',
    description: '',
    sort: '23',
  },
  {
    name: '1003',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '57',
    view: true,
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartments/1003/1.jpg',
      '/assets/apartments/1003/2.jpg',
      '/assets/apartments/1003/3.jpg',
      '/assets/apartments/1003/4.jpg',
      '/assets/apartments/1003/5.jpg',
      '/assets/apartments/1003/6.jpg',
      '/assets/apartments/1003/7.jpg',
      '/assets/apartments/1003/8.jpg',
    ],
    summerPrice: '10 000',
    winterPrice: '5 000',
    rooms: '2',
    floor: '10',
    description: '',
    sort: '22',
  },
  {
    name: '907',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '57',
    view: true,
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartments/907/1.jpg',
      '/assets/apartments/907/2.jpg',
      '/assets/apartments/907/3.jpg',
      '/assets/apartments/907/4.jpg',
      '/assets/apartments/907/5.jpg',
      '/assets/apartments/907/6.jpg',
      '/assets/apartments/907/7.jpg',
      '/assets/apartments/907/8.jpg',
    ],
    summerPrice: '11 000',
    winterPrice: '6 000',
    rooms: '2',
    floor: '9',
    description: '',
    sort: '21',
  },
  {
    name: '805',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '57',
    view: true,
    hairDryer: true,
    dishwasher: true,
    oven: false,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartments/805/1.jpg',
      '/assets/apartments/805/2.jpg',
      '/assets/apartments/805/3.jpg',
      '/assets/apartments/805/4.jpg',
      '/assets/apartments/805/5.jpg',
      '/assets/apartments/805/6.jpg',
      '/assets/apartments/805/7.jpg',
      '/assets/apartments/805/8.jpg',
    ],
    summerPrice: '10 000',
    winterPrice: '6 000',
    rooms: '2',
    floor: '8',
    description: '',
    sort: '20',
  },
  {
    name: '716',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '57',
    view: true,
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartments/716/1.jpg',
      '/assets/apartments/716/2.jpg',
      '/assets/apartments/716/3.jpg',
      '/assets/apartments/716/4.jpg',
      '/assets/apartments/716/5.jpg',
      '/assets/apartments/716/6.jpg',
      '/assets/apartments/716/7.jpg',
      '/assets/apartments/716/8.jpg',
    ],
    summerPrice: '10 000',
    winterPrice: '6 500',
    rooms: '2',
    floor: '7',
    description: '',
    sort: '19',
  },
  {
    name: '715',
    balcony: false,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '57',
    view: true,
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartments/715/1.jpg',
      '/assets/apartments/715/2.jpg',
      '/assets/apartments/715/3.jpg',
      '/assets/apartments/715/4.jpg',
      '/assets/apartments/715/5.jpg',
      '/assets/apartments/715/6.jpg',
      '/assets/apartments/715/7.jpg',
      '/assets/apartments/715/8.jpg',
    ],
    summerPrice: '10 000',
    winterPrice: '6 500',
    rooms: '2',
    floor: '7',
    description: '',
    sort: '18',
  },
  {
    name: '712',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '57',
    view: true,
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartments/712/1.jpg',
      '/assets/apartments/712/2.jpg',
      '/assets/apartments/712/3.jpg',
      '/assets/apartments/712/4.jpg',
      '/assets/apartments/712/5.jpg',
      '/assets/apartments/712/6.jpg',
      '/assets/apartments/712/7.jpg',
      '/assets/apartments/712/8.jpg',
    ],
    summerPrice: '10 000',
    winterPrice: '6 500',
    rooms: '2',
    floor: '7',
    description: '',
    sort: '17',
  },
  {
    name: '709',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '54',
    view: true,
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartments/709/1.jpg',
      '/assets/apartments/709/2.jpg',
      '/assets/apartments/709/3.jpg',
      '/assets/apartments/709/4.jpg',
      '/assets/apartments/709/5.jpg',
      '/assets/apartments/709/6.jpg',
      '/assets/apartments/709/7.jpg',
      '/assets/apartments/709/8.jpg',
    ],
    summerPrice: '10 000',
    winterPrice: '6 000',
    rooms: '2',
    floor: '7',
    description: '',
    sort: '16',
  },
  {
    name: '705',
    balcony: true,
    studio: true,
    oneRoom: false,
    twoRoom: false,
    threeRoom: false,
    squareMeters: '53',
    view: true,
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartments/705/1.jpg',
      '/assets/apartments/705/2.jpg',
      '/assets/apartments/705/3.jpg',
      '/assets/apartments/705/4.jpg',
      '/assets/apartments/705/5.jpg',
      '/assets/apartments/705/6.jpg',
      '/assets/apartments/705/7.jpg',
      '/assets/apartments/705/8.jpg',
    ],
    summerPrice: '9 000',
    winterPrice: '5 000',
    rooms: 'Студия',
    floor: '7',
    description: '',
    sort: '15',
  },
  {
    name: '613',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '55',
    view: false,
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: true,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartments/613/1.jpg',
      '/assets/apartments/613/2.jpg',
      '/assets/apartments/613/3.jpg',
      '/assets/apartments/613/4.jpg',
      '/assets/apartments/613/5.jpg',
      '/assets/apartments/613/6.jpg',
      '/assets/apartments/613/7.jpg',
      '/assets/apartments/613/8.jpg',
    ],
    summerPrice: '10 000',
    winterPrice: '6 000',
    rooms: '2',
    floor: '6',
    description: '',
    sort: '14',
  },
  {
    name: '612',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '55',
    view: false,
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '5',
    wifi: true,
    coffeeMachine: true,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartments/612/1.jpg',
      '/assets/apartments/612/2.jpg',
      '/assets/apartments/612/3.jpg',
      '/assets/apartments/612/4.jpg',
      '/assets/apartments/612/5.jpg',
      '/assets/apartments/612/6.jpg',
      '/assets/apartments/612/7.jpg',
      '/assets/apartments/612/8.jpg',
    ],
    summerPrice: '11 000',
    winterPrice: '6 000',
    rooms: '2',
    floor: '6',
    description: '',
    sort: '13',
  },
  {
    name: '607',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '53',
    view: false,
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: true,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartments/607/1.jpg',
      '/assets/apartments/607/2.jpg',
      '/assets/apartments/607/3.jpg',
      '/assets/apartments/607/4.jpg',
      '/assets/apartments/607/5.jpg',
      '/assets/apartments/607/6.jpg',
      '/assets/apartments/607/7.jpg',
      '/assets/apartments/607/8.jpg',
    ],
    summerPrice: '10 000',
    winterPrice: '6 000',
    rooms: '2',
    floor: '6',
    description: '',
    sort: '12',
  },
  {
    name: '606',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '53',
    view: false,
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartments/606/1.jpg',
      '/assets/apartments/606/2.jpg',
      '/assets/apartments/606/3.jpg',
      '/assets/apartments/606/4.jpg',
      '/assets/apartments/606/5.jpg',
      '/assets/apartments/606/6.jpg',
      '/assets/apartments/606/7.jpg',
      '/assets/apartments/606/8.jpg',
    ],
    summerPrice: '9 000',
    winterPrice: '5 000',
    rooms: '2',
    floor: '6',
    description: '',
    sort: '11',
  },
  {
    name: '605',
    balcony: true,
    studio: true,
    oneRoom: false,
    twoRoom: false,
    threeRoom: false,
    squareMeters: '50',
    view: false,
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartments/605/1.jpg',
      '/assets/apartments/605/2.jpg',
      '/assets/apartments/605/3.jpg',
      '/assets/apartments/605/4.jpg',
      '/assets/apartments/605/5.jpg',
      '/assets/apartments/605/6.jpg',
      '/assets/apartments/605/7.jpg',
      '/assets/apartments/605/8.jpg',
    ],
    summerPrice: '8 500',
    winterPrice: '5 000',
    rooms: 'Студия',
    floor: '6',
    description: '',
    sort: '10',
  },
  {
    name: '509',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '57',
    view: false,
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '5',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartments/310/1.jpg',
      '/assets/apartments/310/2.jpg',
      '/assets/apartments/310/3.jpg',
      '/assets/apartments/310/4.jpg',
      '/assets/apartments/310/5.jpg',
      '/assets/apartments/310/6.jpg',
      '/assets/apartments/310/7.jpg',
      '/assets/apartments/310/8.jpg',
    ],
    summerPrice: '10 000',
    winterPrice: '6 000',
    rooms: '2',
    floor: '5',
    description: '',
    sort: '9',
  },
  {
    name: '503',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '52',
    view: false,
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartments/503/1.jpg',
      '/assets/apartments/503/2.jpg',
      '/assets/apartments/503/3.jpg',
      '/assets/apartments/503/4.jpg',
      '/assets/apartments/503/5.jpg',
      '/assets/apartments/503/6.jpg',
      '/assets/apartments/503/7.jpg',
      '/assets/apartments/503/8.jpg',
    ],
    summerPrice: '9 000',
    winterPrice: '5 000',
    rooms: '2',
    floor: '5',
    description: '',
    sort: '8',
  },
  {
    name: '416',
    balcony: true,
    studio: false,
    oneRoom: true,
    twoRoom: false,
    threeRoom: false,
    squareMeters: '45',
    view: false,
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartments/416/1.jpg',
      '/assets/apartments/416/2.jpg',
      '/assets/apartments/416/3.jpg',
      '/assets/apartments/416/4.jpg',
      '/assets/apartments/416/5.jpg',
      '/assets/apartments/416/6.jpg',
      '/assets/apartments/416/7.jpg',
      '/assets/apartments/416/8.jpg',
    ],
    summerPrice: '8 500',
    winterPrice: '5 000',
    rooms: '1',
    floor: '4',
    description: '',
    sort: '7',
  },
  {
    name: '415',
    balcony: false,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '45',
    view: false,
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartments/415/1.jpg',
      '/assets/apartments/415/2.jpg',
      '/assets/apartments/415/3.jpg',
      '/assets/apartments/415/4.jpg',
      '/assets/apartments/415/5.jpg',
      '/assets/apartments/415/6.jpg',
      '/assets/apartments/415/7.jpg',
      '/assets/apartments/415/8.jpg',
    ],
    summerPrice: '8 000',
    winterPrice: '4 500',
    rooms: '2',
    floor: '4',
    description: '',
    sort: '6',
  },
  {
    name: '402',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: false,
    threeRoom: true,
    squareMeters: '57',
    view: false,
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '6',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartments/402/1.jpg',
      '/assets/apartments/402/2.jpg',
      '/assets/apartments/402/3.jpg',
      '/assets/apartments/402/4.jpg',
      '/assets/apartments/402/5.jpg',
      '/assets/apartments/402/6.jpg',
      '/assets/apartments/402/7.jpg',
      '/assets/apartments/402/8.jpg',
    ],
    summerPrice: '10 000',
    winterPrice: '5 000',
    rooms: '3',
    floor: '4',
    description: '',
    sort: '5',
  },
  {
    name: '312',
    balcony: true,
    studio: false,
    oneRoom: true,
    twoRoom: false,
    threeRoom: false,
    squareMeters: '45',
    view: false,
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartments/312/1.jpg',
      '/assets/apartments/312/2.jpg',
      '/assets/apartments/312/3.jpg',
      '/assets/apartments/312/4.jpg',
      '/assets/apartments/312/5.jpg',
      '/assets/apartments/312/6.jpg',
      '/assets/apartments/312/7.jpg',
      '/assets/apartments/312/8.jpg',
    ],
    summerPrice: '9 000',
    winterPrice: '6 000',
    rooms: '1',
    floor: '3',
    description: '',
    sort: '4',
  },
  {
    name: '310',
    balcony: false,
    studio: false,
    oneRoom: true,
    twoRoom: false,
    threeRoom: false,
    squareMeters: '45',
    view: false,
    hairDryer: true,
    dishwasher: false,
    oven: true,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartments/310/1.jpg',
      '/assets/apartments/310/2.jpg',
      '/assets/apartments/310/3.jpg',
      '/assets/apartments/310/4.jpg',
      '/assets/apartments/310/5.jpg',
      '/assets/apartments/310/6.jpg',
      '/assets/apartments/310/7.jpg',
      '/assets/apartments/310/8.jpg',
    ],
    summerPrice: '9 000',
    winterPrice: '5 000',
    rooms: '1',
    floor: '3',
    description: '',
    sort: '3',
  },
  {
    name: '21/8',
    balcony: false,
    studio: false,
    oneRoom: false,
    twoRoom: false,
    threeRoom: true,
    squareMeters: '48',
    view: false,
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '6',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartments/21-8/1.jpg',
      '/assets/apartments/21-8/2.jpg',
      '/assets/apartments/21-8/3.jpg',
      '/assets/apartments/21-8/4.jpg',
      '/assets/apartments/21-8/5.jpg',
      '/assets/apartments/21-8/6.jpg',
      '/assets/apartments/21-8/7.jpg',
      '/assets/apartments/21-8/8.jpg',
    ],
    summerPrice: '10 000',
    winterPrice: '6 000',
    rooms: '3',
    floor: '1',
    description: '',
    sort: '2',
  },
  {
    name: '21/6',
    balcony: false,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '48',
    view: false,
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartments/21-6/1.jpg',
      '/assets/apartments/21-6/2.jpg',
      '/assets/apartments/21-6/3.jpg',
      '/assets/apartments/21-6/4.jpg',
      '/assets/apartments/21-6/5.jpg',
      '/assets/apartments/21-6/6.jpg',
      '/assets/apartments/21-6/7.jpg',
      '/assets/apartments/21-6/8.jpg',
    ],
    summerPrice: '10 000',
    winterPrice: '6 000',
    rooms: '2',
    floor: '1',
    description: '',
    sort: '1',
  },
];
