export const table1 = [
  {
    name: '1416',
    balcony: false,
    studio: false,
    oneRoom: false,
    twoRoom: false,
    threeRoom: true,
    squareMeters: '60',
    view: true,
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '6',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      {
        img: '/assets/apartments/1416/1.jpg',
        id: '1416-0',
      },
      {
        img: '/assets/apartments/1416/2.jpg',
        id: '1416-1',
      },
      {
        img: '/assets/apartments/1416/3.jpg',
        id: '1416-2',
      },
      {
        img: '/assets/apartments/1416/4.jpg',
        id: '1416-3',
      },
      {
        img: '/assets/apartments/1416/5.jpg',
        id: '1416-4',
      },
      {
        img: '/assets/apartments/1416/6.jpg',
        id: '1416-5',
      },
      {
        img: '/assets/apartments/1416/7.jpg',
        id: '1416-6',
      },
      {
        img: '/assets/apartments/1416/8.jpg',
        id: '1416-7',
      },
    ],
    summerPrice: '12 000',
    winterPrice: '6 000',
    rooms: '3',
    floor: '14',
    meta: {
      title: 'Апартамент 1416',
      description:
        'Забронировать апартамент площадью 60 кв. м., 6 спальных мест, 14 этаж, с видом на море в Сочи',
      keywords: 'Апартамент 1416, Барселона парк, Апартамент Сочи',
    },
    sort: '42',
  },
  {
    name: '1415',
    balcony: false,
    studio: false,
    oneRoom: false,
    twoRoom: false,
    threeRoom: true,
    squareMeters: '60',
    view: true,
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '6',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      {
        img: '/assets/apartments/1415/1.jpg',
        id: '1415-0',
      },
      {
        img: '/assets/apartments/1415/2.jpg',
        id: '1415-1',
      },
      {
        img: '/assets/apartments/1415/3.jpg',
        id: '1415-2',
      },
      {
        img: '/assets/apartments/1415/4.jpg',
        id: '1415-3',
      },
      {
        img: '/assets/apartments/1415/5.jpg',
        id: '1415-4',
      },
      {
        img: '/assets/apartments/1415/6.jpg',
        id: '1415-5',
      },
      {
        img: '/assets/apartments/1415/7.jpg',
        id: '1415-6',
      },
      {
        img: '/assets/apartments/1415/8.jpg',
        id: '1415-7',
      },
    ],
    summerPrice: '12 000',
    winterPrice: '6 000',
    rooms: '3',
    floor: '14',
    meta: {
      title: 'Апартамент 1415',
      description:
        'Забронировать апартамент площадью 60 кв. м., 6 спальных мест, 14 этаж, с видом на море в Сочи',
      keywords: 'Апартамент 1415, Барселона парк, Апартамент Сочи',
    },
    sort: '41',
  },
  {
    name: '1410',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '54',
    view: true,
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: true,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      {
        img: '/assets/apartments/1410/1.jpg',
        id: '1410-0',
      },
      {
        img: '/assets/apartments/1410/2.jpg',
        id: '1410-1',
      },
      {
        img: '/assets/apartments/1410/3.jpg',
        id: '1410-2',
      },
      {
        img: '/assets/apartments/1410/4.jpg',
        id: '1410-3',
      },
      {
        img: '/assets/apartments/1410/5.jpg',
        id: '1410-4',
      },
      {
        img: '/assets/apartments/1410/6.jpg',
        id: '1410-5',
      },
      {
        img: '/assets/apartments/1410/7.jpg',
        id: '1410-6',
      },
      {
        img: '/assets/apartments/1410/8.jpg',
        id: '1410-7',
      },
    ],
    summerPrice: '12 000',
    winterPrice: '6 000',
    rooms: '2',
    floor: '14',
    meta: {
      title: 'Апартамент 1410',
      description:
        'Забронировать апартамент площадью 54 кв. м., 4 спальных места, 14 этаж, с видом на море в Сочи',
      keywords: 'Апартамент 1410, Барселона парк, Апартамент Сочи',
    },
    sort: '40',
  },
  {
    name: '1409',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '50',
    view: true,
    hairDryer: true,
    dishwasher: false,
    oven: true,
    sleepingPlaces: '3',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      {
        img: '/assets/apartments/1409/1.jpg',
        id: '1409-0',
      },
      {
        img: '/assets/apartments/1409/2.jpg',
        id: '1409-1',
      },
      {
        img: '/assets/apartments/1409/3.jpg',
        id: '1409-2',
      },
      {
        img: '/assets/apartments/1409/4.jpg',
        id: '1409-3',
      },
      {
        img: '/assets/apartments/1409/5.jpg',
        id: '1409-4',
      },
      {
        img: '/assets/apartments/1409/6.jpg',
        id: '1409-5',
      },
      {
        img: '/assets/apartments/1409/7.jpg',
        id: '1409-6',
      },
      {
        img: '/assets/apartments/1409/8.jpg',
        id: '1409-7',
      },
    ],
    summerPrice: '12 000',
    winterPrice: '6 000',
    rooms: '2',
    floor: '14',
    meta: {
      title: 'Апартамент 1409',
      description:
        'Забронировать апартамент площадью 50 кв. м., 3 спальных места, 14 этаж, с видом на море в Сочи',
      keywords: 'Апартамент 1409, Барселона парк, Апартамент Сочи',
    },
    sort: '39',
  },
  {
    name: '1404',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '50',
    view: true,
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      {
        img: '/assets/apartments/1404/1.jpg',
        id: '1404-0',
      },
      {
        img: '/assets/apartments/1404/2.jpg',
        id: '1404-1',
      },
      {
        img: '/assets/apartments/1404/3.jpg',
        id: '1404-2',
      },
      {
        img: '/assets/apartments/1404/4.jpg',
        id: '1404-3',
      },
      {
        img: '/assets/apartments/1404/5.jpg',
        id: '1404-4',
      },
      {
        img: '/assets/apartments/1404/6.jpg',
        id: '1404-5',
      },
      {
        img: '/assets/apartments/1404/7.jpg',
        id: '1404-6',
      },
      {
        img: '/assets/apartments/1404/8.jpg',
        id: '1404-7',
      },
    ],
    summerPrice: '15 000',
    winterPrice: '6 000',
    rooms: '2',
    floor: '14',
    meta: {
      title: 'Апартамент 1404',
      description:
        'Забронировать апартамент площадью 50 кв. м., 4 спальных места, 14 этаж, с видом на море в Сочи',
      keywords: 'Апартамент 1404, Барселона парк, Апартамент Сочи',
    },
    sort: '38',
  },
  {
    name: '1313',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: false,
    threeRoom: true,
    squareMeters: '58',
    view: true,
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '6',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      {
        img: '/assets/apartments/1313/1.jpg',
        id: '1313-0',
      },
      {
        img: '/assets/apartments/1313/2.jpg',
        id: '1313-1',
      },
      {
        img: '/assets/apartments/1313/3.jpg',
        id: '1313-2',
      },
      {
        img: '/assets/apartments/1313/4.jpg',
        id: '1313-3',
      },
      {
        img: '/assets/apartments/1313/5.jpg',
        id: '1313-4',
      },
      {
        img: '/assets/apartments/1313/6.jpg',
        id: '1313-5',
      },
      {
        img: '/assets/apartments/1313/7.jpg',
        id: '1313-6',
      },
      {
        img: '/assets/apartments/1313/8.jpg',
        id: '1313-7',
      },
    ],
    summerPrice: '12 500',
    winterPrice: '7 000',
    rooms: '3',
    floor: '13',
    meta: {
      title: 'Апартамент 1313',
      description:
        'Забронировать апартамент площадью 58 кв. м., 6 спальных мест, 13 этаж, с видом на море в Сочи',
      keywords: 'Апартамент 1313, Барселона парк, Апартамент Сочи',
    },
    sort: '37',
  },
  {
    name: '1305',
    balcony: false,
    studio: false,
    oneRoom: false,
    twoRoom: false,
    threeRoom: true,
    squareMeters: '59',
    view: false,
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '6',
    wifi: true,
    coffeeMachine: true,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      {
        img: '/assets/apartments/1304 - 1305/1.jpg',
        id: '1305-0',
      },
      {
        img: '/assets/apartments/1304 - 1305/2.jpg',
        id: '1305-1',
      },
      {
        img: '/assets/apartments/1304 - 1305/3.jpg',
        id: '1305-2',
      },
      {
        img: '/assets/apartments/1304 - 1305/4.jpg',
        id: '1305-3',
      },
      {
        img: '/assets/apartments/1304 - 1305/5.jpg',
        id: '1305-4',
      },
      {
        img: '/assets/apartments/1304 - 1305/6.jpg',
        id: '1305-5',
      },
      {
        img: '/assets/apartments/1304 - 1305/7.jpg',
        id: '1305-6',
      },
      {
        img: '/assets/apartments/1304 - 1305/8.jpg',
        id: '1305-7',
      },
    ],
    summerPrice: '12 000',
    winterPrice: '6 000',
    rooms: '3',
    floor: '13',
    meta: {
      title: 'Апартамент 1305',
      description:
        'Забронировать апартамент площадью 59 кв. м., 6 спальных мест, 13 этаж, с видом на город в Сочи',
      keywords: 'Апартамент 1305, Барселона парк, Апартамент Сочи',
    },
    sort: '36',
  },
  {
    name: '1304',
    balcony: false,
    studio: false,
    oneRoom: false,
    twoRoom: false,
    threeRoom: true,
    squareMeters: '59',
    view: false,
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '1',
    wifi: true,
    coffeeMachine: true,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      {
        img: '/assets/apartments/1304 - 1305/1.jpg',
        id: '1304-0',
      },
      {
        img: '/assets/apartments/1304 - 1305/2.jpg',
        id: '1304-1',
      },
      {
        img: '/assets/apartments/1304 - 1305/3.jpg',
        id: '1304-2',
      },
      {
        img: '/assets/apartments/1304 - 1305/4.jpg',
        id: '1304-3',
      },
      {
        img: '/assets/apartments/1304 - 1305/5.jpg',
        id: '1304-4',
      },
      {
        img: '/assets/apartments/1304 - 1305/6.jpg',
        id: '1304-5',
      },
      {
        img: '/assets/apartments/1304 - 1305/7.jpg',
        id: '1304-6',
      },
      {
        img: '/assets/apartments/1304 - 1305/8.jpg',
        id: '1304-7',
      },
    ],
    summerPrice: '12 000',
    winterPrice: '6 000',
    rooms: '3',
    floor: '13',
    meta: {
      title: 'Апартамент 1304',
      description:
        'Забронировать апартамент площадью 58 кв. м., 6 спальных мест, 13 этаж, с видом на город в Сочи',
      keywords: 'Апартамент 1304, Барселона парк, Апартамент Сочи',
    },
    sort: '35',
  },
  {
    name: '1303',
    balcony: true,
    studio: true,
    oneRoom: false,
    twoRoom: false,
    threeRoom: false,
    squareMeters: '52',
    view: true,
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: true,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      {
        img: '/assets/apartments/1303/1.jpg',
        id: '1303-0',
      },
      {
        img: '/assets/apartments/1303/2.jpg',
        id: '1303-1',
      },
      {
        img: '/assets/apartments/1303/3.jpg',
        id: '1303-2',
      },
      {
        img: '/assets/apartments/1303/4.jpg',
        id: '1303-3',
      },
      {
        img: '/assets/apartments/1303/5.jpg',
        id: '1303-4',
      },
      {
        img: '/assets/apartments/1303/6.jpg',
        id: '1303-5',
      },
      {
        img: '/assets/apartments/1303/7.jpg',
        id: '1303-6',
      },
      {
        img: '/assets/apartments/1303/8.jpg',
        id: '1303-7',
      },
    ],
    summerPrice: '12 000',
    winterPrice: '6 000',
    rooms: 'Студия',
    floor: '13',
    meta: {
      title: 'Апартамент 1303',
      description:
        'Забронировать апартамент площадью 52 кв. м., 4 спальных места, 13 этаж, с видом на море в Сочи',
      keywords: 'Апартамент 1303, Барселона парк, Апартамент Сочи',
    },
    sort: '34',
  },
  {
    name: '1208',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '57',
    view: true,
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      {
        img: '/assets/apartments/1208/1.jpg',
        id: '1208-0',
      },
      {
        img: '/assets/apartments/1208/2.jpg',
        id: '1208-1',
      },
      {
        img: '/assets/apartments/1208/3.jpg',
        id: '1208-2',
      },
      {
        img: '/assets/apartments/1208/4.jpg',
        id: '1208-3',
      },
      {
        img: '/assets/apartments/1208/5.jpg',
        id: '1208-4',
      },
      {
        img: '/assets/apartments/1208/6.jpg',
        id: '1208-5',
      },
      {
        img: '/assets/apartments/1208/7.jpg',
        id: '1208-6',
      },
      {
        img: '/assets/apartments/1208/8.jpg',
        id: '1208-7',
      },
    ],
    summerPrice: '12 000',
    winterPrice: '7 000',
    rooms: '2',
    floor: '12',
    meta: {
      title: 'Апартамент 1208',
      description:
        'Забронировать апартамент площадью 57 кв. м., 4 спальных места, 12 этаж, с видом на море в Сочи',
      keywords: 'Апартамент 1208, Барселона парк, Апартамент Сочи',
    },
    sort: '33',
  },
  {
    name: '1207',
    balcony: true,
    studio: true,
    oneRoom: false,
    twoRoom: false,
    threeRoom: false,
    squareMeters: '57',
    view: true,
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      {
        img: '/assets/apartments/1207/1.jpg',
        id: '1207-0',
      },
      {
        img: '/assets/apartments/1207/2.jpg',
        id: '1207-1',
      },
      {
        img: '/assets/apartments/1207/3.jpg',
        id: '1207-2',
      },
      {
        img: '/assets/apartments/1207/4.jpg',
        id: '1207-3',
      },
      {
        img: '/assets/apartments/1207/5.jpg',
        id: '1207-4',
      },
      {
        img: '/assets/apartments/1207/6.jpg',
        id: '1207-5',
      },
      {
        img: '/assets/apartments/1207/7.jpg',
        id: '1207-6',
      },
      {
        img: '/assets/apartments/1207/8.jpg',
        id: '1207-7',
      },
    ],
    summerPrice: '10 000',
    winterPrice: '6 000',
    rooms: 'Студия',
    floor: '12',
    meta: {
      title: 'Апартамент 1207',
      description:
        'Забронировать апартамент площадью 57 кв. м., 4 спальных места, 12 этаж, с видом на море в Сочи',
      keywords: 'Апартамент 1207, Барселона парк, Апартамент Сочи',
    },
    sort: '32',
  },
  {
    name: '1206',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '57',
    view: true,
    hairDryer: true,
    dishwasher: true,
    oven: false,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      {
        img: '/assets/apartments/1206/1.jpg',
        id: '1206-0',
      },
      {
        img: '/assets/apartments/1206/2.jpg',
        id: '1206-1',
      },
      {
        img: '/assets/apartments/1206/3.jpg',
        id: '1206-2',
      },
      {
        img: '/assets/apartments/1206/4.jpg',
        id: '1206-3',
      },
      {
        img: '/assets/apartments/1206/5.jpg',
        id: '1206-4',
      },
      {
        img: '/assets/apartments/1206/6.jpg',
        id: '1206-5',
      },
      {
        img: '/assets/apartments/1206/7.jpg',
        id: '1206-6',
      },
      {
        img: '/assets/apartments/1206/8.jpg',
        id: '1206-7',
      },
    ],
    summerPrice: '11 000',
    winterPrice: '6 000',
    rooms: '2',
    floor: '12',
    meta: {
      title: 'Апартамент 1206',
      description:
        'Забронировать апартамент площадью 57 кв. м., 4 спальных места, 12 этаж, с видом на море в Сочи',
      keywords: 'Апартамент 1206, Барселона парк, Апартамент Сочи',
    },
    sort: '31',
  },
  {
    name: '1111',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '58',
    view: true,
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      {
        img: '/assets/apartments/1111/1.jpg',
        id: '1111-0',
      },
      {
        img: '/assets/apartments/1111/2.jpg',
        id: '1111-1',
      },
      {
        img: '/assets/apartments/1111/3.jpg',
        id: '1111-2',
      },
      {
        img: '/assets/apartments/1111/4.jpg',
        id: '1111-3',
      },
      {
        img: '/assets/apartments/1111/5.jpg',
        id: '1111-4',
      },
      {
        img: '/assets/apartments/1111/6.jpg',
        id: '1111-5',
      },
      {
        img: '/assets/apartments/1111/7.jpg',
        id: '1111-6',
      },
      {
        img: '/assets/apartments/1111/8.jpg',
        id: '1111-7',
      },
    ],
    summerPrice: '11 000',
    winterPrice: '5 500',
    rooms: '2',
    floor: '11',
    meta: {
      title: 'Апартамент 1111',
      description:
        'Забронировать апартамент площадью 58 кв. м., 4 спальных места, 11 этаж, с видом на море в Сочи',
      keywords: 'Апартамент 1111, Барселона парк, Апартамент Сочи',
    },
    sort: '30',
  },
  {
    name: '1110',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: false,
    threeRoom: true,
    squareMeters: '57',
    view: true,
    hairDryer: true,
    dishwasher: true,
    oven: false,
    sleepingPlaces: '6',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      {
        img: '/assets/apartments/1110/1.jpg',
        id: '1110-0',
      },
      {
        img: '/assets/apartments/1110/2.jpg',
        id: '1110-1',
      },
      {
        img: '/assets/apartments/1110/3.jpg',
        id: '1110-2',
      },
      {
        img: '/assets/apartments/1110/4.jpg',
        id: '1110-3',
      },
      {
        img: '/assets/apartments/1110/5.jpg',
        id: '1110-4',
      },
      {
        img: '/assets/apartments/1110/6.jpg',
        id: '1110-5',
      },
      {
        img: '/assets/apartments/1110/7.jpg',
        id: '1110-6',
      },
      {
        img: '/assets/apartments/1110/8.jpg',
        id: '1110-7',
      },
    ],
    summerPrice: '12 000',
    winterPrice: '6 000',
    rooms: '3',
    floor: '11',
    meta: {
      title: 'Апартамент 1110',
      description:
        'Забронировать апартамент площадью 57 кв. м., 6 спальных мест, 11 этаж, с видом на море в Сочи',
      keywords: 'Апартамент 1110, Барселона парк, Апартамент Сочи',
    },
    sort: '29',
  },
  {
    name: '1109',
    balcony: false,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '56',
    view: true,
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: true,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      {
        img: '/assets/apartments/1109/1.jpg',
        id: '1109-0',
      },
      {
        img: '/assets/apartments/1109/2.jpg',
        id: '1109-1',
      },
      {
        img: '/assets/apartments/1109/3.jpg',
        id: '1109-2',
      },
      {
        img: '/assets/apartments/1109/4.jpg',
        id: '1109-3',
      },
      {
        img: '/assets/apartments/1109/5.jpg',
        id: '1109-4',
      },
      {
        img: '/assets/apartments/1109/6.jpg',
        id: '1109-5',
      },
      {
        img: '/assets/apartments/1109/7.jpg',
        id: '1109-6',
      },
      {
        img: '/assets/apartments/1109/8.jpg',
        id: '1109-7',
      },
    ],
    summerPrice: '10 000',
    winterPrice: '5 000',
    rooms: '2',
    floor: '11',
    meta: {
      title: 'Апартамент 1109',
      description:
        'Забронировать апартамент площадью 56 кв. м., 4 спальных места, 11 этаж, с видом на море в Сочи',
      keywords: 'Апартамент 1109, Барселона парк, Апартамент Сочи',
    },
    sort: '28',
  },
  {
    name: '1105',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '57',
    view: true,
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '6',
    wifi: true,
    coffeeMachine: true,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      {
        img: '/assets/apartments/1104 - 1105/1.jpg',
        id: '1105-0',
      },
      {
        img: '/assets/apartments/1104 - 1105/2.jpg',
        id: '1105-1',
      },
      {
        img: '/assets/apartments/1104 - 1105/3.jpg',
        id: '1105-2',
      },
      {
        img: '/assets/apartments/1104 - 1105/4.jpg',
        id: '1105-3',
      },
      {
        img: '/assets/apartments/1104 - 1105/5.jpg',
        id: '1105-4',
      },
      {
        img: '/assets/apartments/1104 - 1105/6.jpg',
        id: '1105-5',
      },
      {
        img: '/assets/apartments/1104 - 1105/7.jpg',
        id: '1105-6',
      },
      {
        img: '/assets/apartments/1104 - 1105/8.jpg',
        id: '1105-7',
      },
    ],
    summerPrice: '12 000',
    winterPrice: '6 000',
    rooms: '2',
    floor: '11',
    meta: {
      title: 'Апартамент 1105',
      description:
        'Забронировать апартамент площадью 57 кв. м., 6 спальных мест, 11 этаж, с видом на море в Сочи',
      keywords: 'Апартамент 1105, Барселона парк, Апартамент Сочи',
    },
    sort: '27',
  },
  {
    name: '1104',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '57',
    view: true,
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '6',
    wifi: true,
    coffeeMachine: true,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      {
        img: '/assets/apartments/1104 - 1105/1.jpg',
        id: '1104-0',
      },
      {
        img: '/assets/apartments/1104 - 1105/2.jpg',
        id: '1104-1',
      },
      {
        img: '/assets/apartments/1104 - 1105/3.jpg',
        id: '1104-2',
      },
      {
        img: '/assets/apartments/1104 - 1105/4.jpg',
        id: '1104-3',
      },
      {
        img: '/assets/apartments/1104 - 1105/5.jpg',
        id: '1104-4',
      },
      {
        img: '/assets/apartments/1104 - 1105/6.jpg',
        id: '1104-5',
      },
      {
        img: '/assets/apartments/1104 - 1105/7.jpg',
        id: '1104-6',
      },
      {
        img: '/assets/apartments/1104 - 1105/8.jpg',
        id: '1104-7',
      },
    ],
    summerPrice: '12 000',
    winterPrice: '6 000',
    rooms: '2',
    floor: '11',
    meta: {
      title: 'Апартамент 1104',
      description:
        'Забронировать апартамент площадью 57 кв. м., 6 спальных мест, 11 этаж, с видом на море в Сочи',
      keywords: 'Апартамент 1104, Барселона парк, Апартамент Сочи',
    },
    sort: '26',
  },
  {
    name: '1103',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '57',
    view: true,
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '5',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      {
        img: '/assets/apartments/1103/1.jpg',
        id: '1103-0',
      },
      {
        img: '/assets/apartments/1103/2.jpg',
        id: '1103-1',
      },
      {
        img: '/assets/apartments/1103/3.jpg',
        id: '1103-2',
      },
      {
        img: '/assets/apartments/1103/4.jpg',
        id: '1103-3',
      },
      {
        img: '/assets/apartments/1103/5.jpg',
        id: '1103-4',
      },
      {
        img: '/assets/apartments/1103/6.jpg',
        id: '1103-5',
      },
      {
        img: '/assets/apartments/1103/7.jpg',
        id: '1103-6',
      },
      {
        img: '/assets/apartments/1103/8.jpg',
        id: '1103-7',
      },
    ],
    summerPrice: '10 000',
    winterPrice: '5 000',
    rooms: '2',
    floor: '11',
    meta: {
      title: 'Апартамент 1103',
      description:
        'Забронировать апартамент площадью 57 кв. м., 5 спальных мест, 11 этаж, с видом на море в Сочи',
      keywords: 'Апартамент 1103, Барселона парк, Апартамент Сочи',
    },
    sort: '25',
  },
  {
    name: '1014',
    balcony: true,
    studio: false,
    oneRoom: true,
    twoRoom: false,
    threeRoom: false,
    squareMeters: '58',
    view: true,
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '5',
    wifi: true,
    coffeeMachine: true,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      {
        img: '/assets/apartments/1013 - 1014/1.jpg',
        id: '1014-0',
      },
      {
        img: '/assets/apartments/1013 - 1014/2.jpg',
        id: '1014-1',
      },
      {
        img: '/assets/apartments/1013 - 1014/3.jpg',
        id: '1014-2',
      },
      {
        img: '/assets/apartments/1013 - 1014/4.jpg',
        id: '1014-3',
      },
      {
        img: '/assets/apartments/1013 - 1014/5.jpg',
        id: '1014-4',
      },
      {
        img: '/assets/apartments/1013 - 1014/6.jpg',
        id: '1014-5',
      },
      {
        img: '/assets/apartments/1013 - 1014/7.jpg',
        id: '1014-6',
      },
      {
        img: '/assets/apartments/1013 - 1014/8.jpg',
        id: '1014-7',
      },
    ],
    summerPrice: '12 000',
    winterPrice: '7 000',
    rooms: '1',
    floor: '10',
    meta: {
      title: 'Апартамент 1014',
      description:
        'Забронировать апартамент площадью 58 кв. м., 5 спальных мест, 10 этаж, с видом на море в Сочи',
      keywords: 'Апартамент 1014, Барселона парк, Апартамент Сочи',
    },
    sort: '24',
  },
  {
    name: '1013',
    balcony: true,
    studio: false,
    oneRoom: true,
    twoRoom: false,
    threeRoom: false,
    squareMeters: '58',
    view: true,
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '5',
    wifi: true,
    coffeeMachine: true,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      {
        img: '/assets/apartments/1013 - 1014/1.jpg',
        id: '1013-0',
      },
      {
        img: '/assets/apartments/1013 - 1014/2.jpg',
        id: '1013-1',
      },
      {
        img: '/assets/apartments/1013 - 1014/3.jpg',
        id: '1013-2',
      },
      {
        img: '/assets/apartments/1013 - 1014/4.jpg',
        id: '1013-3',
      },
      {
        img: '/assets/apartments/1013 - 1014/5.jpg',
        id: '1013-4',
      },
      {
        img: '/assets/apartments/1013 - 1014/6.jpg',
        id: '1013-5',
      },
      {
        img: '/assets/apartments/1013 - 1014/7.jpg',
        id: '1013-6',
      },
      {
        img: '/assets/apartments/1013 - 1014/8.jpg',
        id: '1013-7',
      },
    ],
    summerPrice: '12 000',
    winterPrice: '7 000',
    rooms: '1',
    floor: '10',
    meta: {
      title: 'Апартамент 1013',
      description:
        'Забронировать апартамент площадью 58 кв. м., 5 спальных мест, 10 этаж, с видом на море в Сочи',
      keywords: 'Апартамент 1013, Барселона парк, Апартамент Сочи',
    },
    sort: '23',
  },
  {
    name: '1003',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '57',
    view: true,
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      {
        img: '/assets/apartments/1003/1.jpg',
        id: '1003-0',
      },
      {
        img: '/assets/apartments/1003/2.jpg',
        id: '1003-1',
      },
      {
        img: '/assets/apartments/1003/3.jpg',
        id: '1003-2',
      },
      {
        img: '/assets/apartments/1003/4.jpg',
        id: '1003-3',
      },
      {
        img: '/assets/apartments/1003/5.jpg',
        id: '1003-4',
      },
      {
        img: '/assets/apartments/1003/6.jpg',
        id: '1003-5',
      },
      {
        img: '/assets/apartments/1003/7.jpg',
        id: '1003-6',
      },
      {
        img: '/assets/apartments/1003/8.jpg',
        id: '1003-7',
      },
    ],
    summerPrice: '10 000',
    winterPrice: '5 000',
    rooms: '2',
    floor: '10',
    meta: {
      title: 'Апартамент 1003',
      description:
        'Забронировать апартамент площадью 57 кв. м., 4 спальных места, 10 этаж, с видом на море в Сочи',
      keywords: 'Апартамент 1003, Барселона парк, Апартамент Сочи',
    },
    sort: '22',
  },
  {
    name: '907',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '57',
    view: true,
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      {
        img: '/assets/apartments/907/1.jpg',
        id: '907-0',
      },
      {
        img: '/assets/apartments/907/2.jpg',
        id: '907-1',
      },
      {
        img: '/assets/apartments/907/3.jpg',
        id: '907-2',
      },
      {
        img: '/assets/apartments/907/4.jpg',
        id: '907-3',
      },
      {
        img: '/assets/apartments/907/5.jpg',
        id: '907-4',
      },
      {
        img: '/assets/apartments/907/6.jpg',
        id: '907-5',
      },
      {
        img: '/assets/apartments/907/7.jpg',
        id: '907-6',
      },
      {
        img: '/assets/apartments/907/8.jpg',
        id: '907-7',
      },
    ],
    summerPrice: '11 000',
    winterPrice: '6 000',
    rooms: '2',
    floor: '9',
    meta: {
      title: 'Апартамент 907',
      description:
        'Забронировать апартамент площадью 57 кв. м., 4 спальных места, 9 этаж, с видом на море в Сочи',
      keywords: 'Апартамент 907, Барселона парк, Апартамент Сочи',
    },
    sort: '21',
  },
  {
    name: '805',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '57',
    view: true,
    hairDryer: true,
    dishwasher: true,
    oven: false,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      {
        img: '/assets/apartments/805/1.jpg',
        id: '805-0',
      },
      {
        img: '/assets/apartments/805/2.jpg',
        id: '805-1',
      },
      {
        img: '/assets/apartments/805/3.jpg',
        id: '805-2',
      },
      {
        img: '/assets/apartments/805/4.jpg',
        id: '805-3',
      },
      {
        img: '/assets/apartments/805/5.jpg',
        id: '805-4',
      },
      {
        img: '/assets/apartments/805/6.jpg',
        id: '805-5',
      },
      {
        img: '/assets/apartments/805/7.jpg',
        id: '805-6',
      },
      {
        img: '/assets/apartments/805/8.jpg',
        id: '805-7',
      },
    ],
    summerPrice: '10 000',
    winterPrice: '6 000',
    rooms: '2',
    floor: '8',
    meta: {
      title: 'Апартамент 805',
      description:
        'Забронировать апартамент площадью 57 кв. м., 4 спальных места, 8 этаж, с видом на море в Сочи',
      keywords: 'Апартамент 805, Барселона парк, Апартамент Сочи',
    },
    sort: '20',
  },
  {
    name: '716',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '57',
    view: true,
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      {
        img: '/assets/apartments/716/1.jpg',
        id: '716-0',
      },
      {
        img: '/assets/apartments/716/2.jpg',
        id: '716-1',
      },
      {
        img: '/assets/apartments/716/3.jpg',
        id: '716-2',
      },
      {
        img: '/assets/apartments/716/4.jpg',
        id: '716-3',
      },
      {
        img: '/assets/apartments/716/5.jpg',
        id: '716-4',
      },
      {
        img: '/assets/apartments/716/6.jpg',
        id: '716-5',
      },
      {
        img: '/assets/apartments/716/7.jpg',
        id: '716-6',
      },
      {
        img: '/assets/apartments/716/8.jpg',
        id: '716-7',
      },
    ],
    summerPrice: '10 000',
    winterPrice: '6 500',
    rooms: '2',
    floor: '7',
    meta: {
      title: 'Апартамент 716',
      description:
        'Забронировать апартамент площадью 57 кв. м., 4 спальных места, 7 этаж, с видом на море в Сочи',
      keywords: 'Апартамент 716, Барселона парк, Апартамент Сочи',
    },
    sort: '19',
  },
  {
    name: '715',
    balcony: false,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '57',
    view: true,
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      {
        img: '/assets/apartments/715/1.jpg',
        id: '715-0',
      },
      {
        img: '/assets/apartments/715/2.jpg',
        id: '715-1',
      },
      {
        img: '/assets/apartments/715/3.jpg',
        id: '715-2',
      },
      {
        img: '/assets/apartments/715/4.jpg',
        id: '715-3',
      },
      {
        img: '/assets/apartments/715/5.jpg',
        id: '715-4',
      },
      {
        img: '/assets/apartments/715/6.jpg',
        id: '715-5',
      },
      {
        img: '/assets/apartments/715/7.jpg',
        id: '715-6',
      },
      {
        img: '/assets/apartments/715/8.jpg',
        id: '715-7',
      },
    ],
    summerPrice: '10 000',
    winterPrice: '6 500',
    rooms: '2',
    floor: '7',
    meta: {
      title: 'Апартамент 715',
      description:
        'Забронировать апартамент площадью 57 кв. м., 4 спальных места, 7 этаж, с видом на море в Сочи',
      keywords: 'Апартамент 715, Барселона парк, Апартамент Сочи',
    },
    sort: '18',
  },
  {
    name: '712',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '57',
    view: true,
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      {
        img: '/assets/apartments/712/1.jpg',
        id: '712-0',
      },
      {
        img: '/assets/apartments/712/2.jpg',
        id: '712-1',
      },
      {
        img: '/assets/apartments/712/3.jpg',
        id: '712-2',
      },
      {
        img: '/assets/apartments/712/4.jpg',
        id: '712-3',
      },
      {
        img: '/assets/apartments/712/5.jpg',
        id: '712-4',
      },
      {
        img: '/assets/apartments/712/6.jpg',
        id: '712-5',
      },
      {
        img: '/assets/apartments/712/7.jpg',
        id: '712-6',
      },
      {
        img: '/assets/apartments/712/8.jpg',
        id: '712-7',
      },
    ],
    summerPrice: '10 000',
    winterPrice: '6 500',
    rooms: '2',
    floor: '7',
    meta: {
      title: 'Апартамент 712',
      description:
        'Забронировать апартамент площадью 57 кв. м., 4 спальных места, 7 этаж, с видом на море в Сочи',
      keywords: 'Апартамент 712, Барселона парк, Апартамент Сочи',
    },
    sort: '17',
  },
  {
    name: '709',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '54',
    view: true,
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      {
        img: '/assets/apartments/709/1.jpg',
        id: '709-0',
      },
      {
        img: '/assets/apartments/709/2.jpg',
        id: '709-1',
      },
      {
        img: '/assets/apartments/709/3.jpg',
        id: '709-2',
      },
      {
        img: '/assets/apartments/709/4.jpg',
        id: '709-3',
      },
      {
        img: '/assets/apartments/709/5.jpg',
        id: '709-4',
      },
      {
        img: '/assets/apartments/709/6.jpg',
        id: '709-5',
      },
      {
        img: '/assets/apartments/709/7.jpg',
        id: '709-6',
      },
      {
        img: '/assets/apartments/709/8.jpg',
        id: '709-7',
      },
    ],
    summerPrice: '10 000',
    winterPrice: '6 000',
    rooms: '2',
    floor: '7',
    meta: {
      title: 'Апартамент 709',
      description:
        'Забронировать апартамент площадью 54 кв. м., 4 спальных места, 7 этаж, с видом на море в Сочи',
      keywords: 'Апартамент 709, Барселона парк, Апартамент Сочи',
    },
    sort: '16',
  },
  {
    name: '705',
    balcony: true,
    studio: true,
    oneRoom: false,
    twoRoom: false,
    threeRoom: false,
    squareMeters: '53',
    view: true,
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      {
        img: '/assets/apartments/705/1.jpg',
        id: '705-0',
      },
      {
        img: '/assets/apartments/705/2.jpg',
        id: '705-1',
      },
      {
        img: '/assets/apartments/705/3.jpg',
        id: '705-2',
      },
      {
        img: '/assets/apartments/705/4.jpg',
        id: '705-3',
      },
      {
        img: '/assets/apartments/705/5.jpg',
        id: '705-4',
      },
      {
        img: '/assets/apartments/705/6.jpg',
        id: '705-5',
      },
      {
        img: '/assets/apartments/705/7.jpg',
        id: '705-6',
      },
      {
        img: '/assets/apartments/705/8.jpg',
        id: '705-7',
      },
    ],
    summerPrice: '9 000',
    winterPrice: '5 000',
    rooms: 'Студия',
    floor: '7',
    meta: {
      title: 'Апартамент 705',
      description:
        'Забронировать апартамент площадью 53 кв. м., 4 спальных места, 7 этаж, с видом на море в Сочи',
      keywords: 'Апартамент 705, Барселона парк, Апартамент Сочи',
    },
    sort: '15',
  },
  {
    name: '613',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '55',
    view: false,
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: true,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      {
        img: '/assets/apartments/613/1.jpg',
        id: '613-0',
      },
      {
        img: '/assets/apartments/613/2.jpg',
        id: '613-1',
      },
      {
        img: '/assets/apartments/613/3.jpg',
        id: '613-2',
      },
      {
        img: '/assets/apartments/613/4.jpg',
        id: '613-3',
      },
      {
        img: '/assets/apartments/613/5.jpg',
        id: '613-4',
      },
      {
        img: '/assets/apartments/613/6.jpg',
        id: '613-5',
      },
      {
        img: '/assets/apartments/613/7.jpg',
        id: '613-6',
      },
      {
        img: '/assets/apartments/613/8.jpg',
        id: '613-7',
      },
    ],
    summerPrice: '10 000',
    winterPrice: '6 000',
    rooms: '2',
    floor: '6',
    meta: {
      title: 'Апартамент 613',
      description:
        'Забронировать апартамент площадью 57 кв. м., 4 спальных места, 6 этаж, с видом на город в Сочи',
      keywords: 'Апартамент 613, Барселона парк, Апартамент Сочи',
    },
    sort: '14',
  },
  {
    name: '612',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '55',
    view: false,
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '5',
    wifi: true,
    coffeeMachine: true,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      {
        img: '/assets/apartments/612/1.jpg',
        id: '612-0',
      },
      {
        img: '/assets/apartments/612/2.jpg',
        id: '612-1',
      },
      {
        img: '/assets/apartments/612/3.jpg',
        id: '612-2',
      },
      {
        img: '/assets/apartments/612/4.jpg',
        id: '612-3',
      },
      {
        img: '/assets/apartments/612/5.jpg',
        id: '612-4',
      },
      {
        img: '/assets/apartments/612/6.jpg',
        id: '612-5',
      },
      {
        img: '/assets/apartments/612/7.jpg',
        id: '612-6',
      },
      {
        img: '/assets/apartments/612/8.jpg',
        id: '612-7',
      },
    ],
    summerPrice: '11 000',
    winterPrice: '6 000',
    rooms: '2',
    floor: '6',
    meta: {
      title: 'Апартамент 612',
      description:
        'Забронировать апартамент площадью 55 кв. м., 5 спальных мест, 6 этаж, с видом на город в Сочи',
      keywords: 'Апартамент 612, Барселона парк, Апартамент Сочи',
    },
    sort: '13',
  },
  {
    name: '607',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '53',
    view: false,
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: true,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      {
        img: '/assets/apartments/607/1.jpg',
        id: '607-0',
      },
      {
        img: '/assets/apartments/607/2.jpg',
        id: '607-1',
      },
      {
        img: '/assets/apartments/607/3.jpg',
        id: '607-2',
      },
      {
        img: '/assets/apartments/607/4.jpg',
        id: '607-3',
      },
      {
        img: '/assets/apartments/607/5.jpg',
        id: '607-4',
      },
      {
        img: '/assets/apartments/607/6.jpg',
        id: '607-5',
      },
      {
        img: '/assets/apartments/607/7.jpg',
        id: '607-6',
      },
      {
        img: '/assets/apartments/607/8.jpg',
        id: '607-7',
      },
    ],
    summerPrice: '10 000',
    winterPrice: '6 000',
    rooms: '2',
    floor: '6',
    meta: {
      title: 'Апартамент 607',
      description:
        'Забронировать апартамент площадью 53 кв. м., 4 спальных места, 6 этаж, с видом на город в Сочи',
      keywords: 'Апартамент 607, Барселона парк, Апартамент Сочи',
    },
    sort: '12',
  },
  {
    name: '606',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '53',
    view: false,
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      {
        img: '/assets/apartments/606/1.jpg',
        id: '606-0',
      },
      {
        img: '/assets/apartments/606/2.jpg',
        id: '606-1',
      },
      {
        img: '/assets/apartments/606/3.jpg',
        id: '606-2',
      },
      {
        img: '/assets/apartments/606/4.jpg',
        id: '606-3',
      },
      {
        img: '/assets/apartments/606/5.jpg',
        id: '606-4',
      },
      {
        img: '/assets/apartments/606/6.jpg',
        id: '606-5',
      },
      {
        img: '/assets/apartments/606/7.jpg',
        id: '606-6',
      },
      {
        img: '/assets/apartments/606/8.jpg',
        id: '606-7',
      },
    ],
    summerPrice: '9 000',
    winterPrice: '5 000',
    rooms: '2',
    floor: '6',
    meta: {
      title: 'Апартамент 606',
      description:
        'Забронировать апартамент площадью 53 кв. м., 4 спальных места, 6 этаж, с видом на город в Сочи',
      keywords: 'Апартамент 606, Барселона парк, Апартамент Сочи',
    },
    sort: '11',
  },
  {
    name: '605',
    balcony: true,
    studio: true,
    oneRoom: false,
    twoRoom: false,
    threeRoom: false,
    squareMeters: '50',
    view: false,
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      {
        img: '/assets/apartments/605/1.jpg',
        id: '605-0',
      },
      {
        img: '/assets/apartments/605/2.jpg',
        id: '605-1',
      },
      {
        img: '/assets/apartments/605/3.jpg',
        id: '605-2',
      },
      {
        img: '/assets/apartments/605/4.jpg',
        id: '605-3',
      },
      {
        img: '/assets/apartments/605/5.jpg',
        id: '605-4',
      },
      {
        img: '/assets/apartments/605/6.jpg',
        id: '605-5',
      },
      {
        img: '/assets/apartments/605/7.jpg',
        id: '605-6',
      },
      {
        img: '/assets/apartments/605/8.jpg',
        id: '605-7',
      },
    ],
    summerPrice: '8 500',
    winterPrice: '5 000',
    rooms: 'Студия',
    floor: '6',
    meta: {
      title: 'Апартамент 605',
      description:
        'Забронировать апартамент площадью 50 кв. м., 4 спальных места, 6 этаж, с видом на город в Сочи',
      keywords: 'Апартамент 605, Барселона парк, Апартамент Сочи',
    },
    sort: '10',
  },
  {
    name: '509',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '57',
    view: false,
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '5',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      {
        img: '/assets/apartments/509/1.jpg',
        id: '509-0',
      },
      {
        img: '/assets/apartments/509/2.jpg',
        id: '509-1',
      },
      {
        img: '/assets/apartments/509/3.jpg',
        id: '509-2',
      },
      {
        img: '/assets/apartments/509/4.jpg',
        id: '509-3',
      },
      {
        img: '/assets/apartments/509/5.jpg',
        id: '509-4',
      },
      {
        img: '/assets/apartments/509/6.jpg',
        id: '509-5',
      },
      {
        img: '/assets/apartments/509/7.jpg',
        id: '509-6',
      },
      {
        img: '/assets/apartments/509/8.jpg',
        id: '509-7',
      },
    ],
    summerPrice: '10 000',
    winterPrice: '6 000',
    rooms: '2',
    floor: '5',
    meta: {
      title: 'Апартамент 509',
      description:
        'Забронировать апартамент площадью 57 кв. м., 5 спальных мест, 5 этаж, с видом на город в Сочи',
      keywords: 'Апартамент 509, Барселона парк, Апартамент Сочи',
    },
    sort: '9',
  },
  {
    name: '503',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '52',
    view: false,
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      {
        img: '/assets/apartments/503/1.jpg',
        id: '503-0',
      },
      {
        img: '/assets/apartments/503/2.jpg',
        id: '503-1',
      },
      {
        img: '/assets/apartments/503/3.jpg',
        id: '503-2',
      },
      {
        img: '/assets/apartments/503/4.jpg',
        id: '503-3',
      },
      {
        img: '/assets/apartments/503/5.jpg',
        id: '503-4',
      },
      {
        img: '/assets/apartments/503/6.jpg',
        id: '503-5',
      },
      {
        img: '/assets/apartments/503/7.jpg',
        id: '503-6',
      },
      {
        img: '/assets/apartments/503/8.jpg',
        id: '503-7',
      },
    ],
    summerPrice: '9 000',
    winterPrice: '5 000',
    rooms: '2',
    floor: '5',
    meta: {
      title: 'Апартамент 503',
      description:
        'Забронировать апартамент площадью 52 кв. м., 4 спальных мест, 5 этаж, с видом на город в Сочи',
      keywords: 'Апартамент 503, Барселона парк, Апартамент Сочи',
    },
    sort: '8',
  },
  {
    name: '416',
    balcony: true,
    studio: false,
    oneRoom: true,
    twoRoom: false,
    threeRoom: false,
    squareMeters: '45',
    view: false,
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      {
        img: '/assets/apartments/416/1.jpg',
        id: '416-0',
      },
      {
        img: '/assets/apartments/416/2.jpg',
        id: '416-1',
      },
      {
        img: '/assets/apartments/416/3.jpg',
        id: '416-2',
      },
      {
        img: '/assets/apartments/416/4.jpg',
        id: '416-3',
      },
      {
        img: '/assets/apartments/416/5.jpg',
        id: '416-4',
      },
      {
        img: '/assets/apartments/416/6.jpg',
        id: '416-5',
      },
      {
        img: '/assets/apartments/416/7.jpg',
        id: '416-6',
      },
      {
        img: '/assets/apartments/416/8.jpg',
        id: '416-7',
      },
    ],
    summerPrice: '8 500',
    winterPrice: '5 000',
    rooms: '1',
    floor: '4',
    meta: {
      title: 'Апартамент 416',
      description:
        'Забронировать апартамент площадью 45 кв. м., 4 спальных места, 4 этаж, с видом на город в Сочи',
      keywords: 'Апартамент 416, Барселона парк, Апартамент Сочи',
    },
    sort: '7',
  },
  {
    name: '415',
    balcony: false,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '45',
    view: false,
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      {
        img: '/assets/apartments/415/1.jpg',
        id: '415-0',
      },
      {
        img: '/assets/apartments/415/2.jpg',
        id: '415-1',
      },
      {
        img: '/assets/apartments/415/3.jpg',
        id: '415-2',
      },
      {
        img: '/assets/apartments/415/4.jpg',
        id: '415-3',
      },
      {
        img: '/assets/apartments/415/5.jpg',
        id: '415-4',
      },
      {
        img: '/assets/apartments/415/6.jpg',
        id: '415-5',
      },
      {
        img: '/assets/apartments/415/7.jpg',
        id: '415-6',
      },
      {
        img: '/assets/apartments/415/8.jpg',
        id: '415-7',
      },
    ],
    summerPrice: '8 000',
    winterPrice: '4 500',
    rooms: '2',
    floor: '4',
    meta: {
      title: 'Апартамент 415',
      description:
        'Забронировать апартамент площадью 45 кв. м., 4 спальных места, 4 этаж, с видом на город в Сочи',
      keywords: 'Апартамент 415, Барселона парк, Апартамент Сочи',
    },
    sort: '6',
  },
  {
    name: '402',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: false,
    threeRoom: true,
    squareMeters: '57',
    view: false,
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '6',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      {
        img: '/assets/apartments/402/1.jpg',
        id: '402-0',
      },
      {
        img: '/assets/apartments/402/2.jpg',
        id: '402-1',
      },
      {
        img: '/assets/apartments/402/3.jpg',
        id: '402-2',
      },
      {
        img: '/assets/apartments/402/4.jpg',
        id: '402-3',
      },
      {
        img: '/assets/apartments/402/5.jpg',
        id: '402-4',
      },
      {
        img: '/assets/apartments/402/6.jpg',
        id: '402-5',
      },
      {
        img: '/assets/apartments/402/7.jpg',
        id: '402-6',
      },
      {
        img: '/assets/apartments/402/8.jpg',
        id: '402-7',
      },
    ],
    summerPrice: '10 000',
    winterPrice: '5 000',
    rooms: '3',
    floor: '4',
    meta: {
      title: 'Апартамент 402',
      description:
        'Забронировать апартамент площадью 57 кв. м., 6 спальных мест, 4 этаж, с видом на город в Сочи',
      keywords: 'Апартамент 402, Барселона парк, Апартамент Сочи',
    },
    sort: '5',
  },
  {
    name: '312',
    balcony: true,
    studio: false,
    oneRoom: true,
    twoRoom: false,
    threeRoom: false,
    squareMeters: '45',
    view: false,
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      {
        img: '/assets/apartments/312/1.jpg',
        id: '312-0',
      },
      {
        img: '/assets/apartments/312/2.jpg',
        id: '312-1',
      },
      {
        img: '/assets/apartments/312/3.jpg',
        id: '312-2',
      },
      {
        img: '/assets/apartments/312/4.jpg',
        id: '312-3',
      },
      {
        img: '/assets/apartments/312/5.jpg',
        id: '312-4',
      },
      {
        img: '/assets/apartments/312/6.jpg',
        id: '312-5',
      },
      {
        img: '/assets/apartments/312/7.jpg',
        id: '312-6',
      },
      {
        img: '/assets/apartments/312/8.jpg',
        id: '312-7',
      },
    ],
    summerPrice: '9 000',
    winterPrice: '6 000',
    rooms: '1',
    floor: '3',
    meta: {
      title: 'Апартамент 312',
      description:
        'Забронировать апартамент площадью 45 кв. м., 4 спальных места, 3 этаж, с видом на город в Сочи',
      keywords: 'Апартамент 312, Барселона парк, Апартамент Сочи',
    },
    sort: '4',
  },
  {
    name: '310',
    balcony: false,
    studio: false,
    oneRoom: true,
    twoRoom: false,
    threeRoom: false,
    squareMeters: '45',
    view: false,
    hairDryer: true,
    dishwasher: false,
    oven: true,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      {
        img: '/assets/apartments/310/1.jpg',
        id: '310-0',
      },
      {
        img: '/assets/apartments/310/2.jpg',
        id: '310-1',
      },
      {
        img: '/assets/apartments/310/3.jpg',
        id: '310-2',
      },
      {
        img: '/assets/apartments/310/4.jpg',
        id: '310-3',
      },
      {
        img: '/assets/apartments/310/5.jpg',
        id: '310-4',
      },
      {
        img: '/assets/apartments/310/6.jpg',
        id: '310-5',
      },
      {
        img: '/assets/apartments/310/7.jpg',
        id: '310-6',
      },
      {
        img: '/assets/apartments/310/8.jpg',
        id: '310-7',
      },
    ],
    summerPrice: '9 000',
    winterPrice: '5 000',
    rooms: '1',
    floor: '3',
    meta: {
      title: 'Апартамент 310',
      description:
        'Забронировать апартамент площадью 45 кв. м., 4 спальных места, 3 этаж, с видом на город в Сочи',
      keywords: 'Апартамент 310, Барселона парк, Апартамент Сочи',
    },
    sort: '3',
  },
  {
    name: '21/8',
    balcony: false,
    studio: false,
    oneRoom: false,
    twoRoom: false,
    threeRoom: true,
    squareMeters: '48',
    view: false,
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '6',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      {
        img: '/assets/apartments/21-8/1.jpg',
        id: '21/8-0',
      },
      {
        img: '/assets/apartments/21-8/2.jpg',
        id: '21/8-1',
      },
      {
        img: '/assets/apartments/21-8/3.jpg',
        id: '21/8-2',
      },
      {
        img: '/assets/apartments/21-8/4.jpg',
        id: '21/8-3',
      },
      {
        img: '/assets/apartments/21-8/5.jpg',
        id: '21/8-4',
      },
      {
        img: '/assets/apartments/21-8/6.jpg',
        id: '21/8-5',
      },
      {
        img: '/assets/apartments/21-8/7.jpg',
        id: '21/8-6',
      },
      {
        img: '/assets/apartments/21-8/8.jpg',
        id: '21/8-7',
      },
    ],
    summerPrice: '10 000',
    winterPrice: '6 000',
    rooms: '3',
    floor: '1',
    meta: {
      title: 'Апартамент 21/8',
      description:
        'Забронировать апартамент площадью 48 кв. м., 6 спальных мест, 1 этаж, с видом на город в Сочи',
      keywords: 'Апартамент 21/8, Барселона парк, Апартамент Сочи',
    },
    sort: '2',
  },
  {
    name: '21/6',
    balcony: false,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '48',
    view: false,
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      {
        img: '/assets/apartments/21-6/1.jpg',
        id: '21/6-0',
      },
      {
        img: '/assets/apartments/21-6/2.jpg',
        id: '21/6-1',
      },
      {
        img: '/assets/apartments/21-6/3.jpg',
        id: '21/6-2',
      },
      {
        img: '/assets/apartments/21-6/4.jpg',
        id: '21/6-3',
      },
      {
        img: '/assets/apartments/21-6/5.jpg',
        id: '21/6-4',
      },
      {
        img: '/assets/apartments/21-6/6.jpg',
        id: '21/6-5',
      },
      {
        img: '/assets/apartments/21-6/7.jpg',
        id: '21/6-6',
      },
      {
        img: '/assets/apartments/21-6/8.jpg',
        id: '21/6-7',
      },
    ],
    summerPrice: '10 000',
    winterPrice: '6 000',
    rooms: '2',
    floor: '1',
    meta: {
      title: 'Апартамент 21/6',
      description:
        'Забронировать апартамент площадью 48 кв. м., 4 спальных места, 1 этаж, с видом на город в Сочи',
      keywords: 'Апартамент 21/6, Барселона парк, Апартамент Сочи',
    },
    sort: '1',
  },
];


export const table = [{
    name: '1416',
    balcony: false,
    studio: false,
    oneRoom: false,
    twoRoom: false,
    threeRoom: true,
    squareMeters: '60',
    view: true,
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '6',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      {
        img: '/assets/apartments/1416/1.jpg',
        id: '1416-0',
      },
      {
        img: '/assets/apartments/1416/2.jpg',
        id: '1416-1',
      },
      {
        img: '/assets/apartments/1416/3.jpg',
        id: '1416-2',
      },
      {
        img: '/assets/apartments/1416/4.jpg',
        id: '1416-3',
      },
      {
        img: '/assets/apartments/1416/5.jpg',
        id: '1416-4',
      },
      {
        img: '/assets/apartments/1416/6.jpg',
        id: '1416-5',
      },
      {
        img: '/assets/apartments/1416/7.jpg',
        id: '1416-6',
      },
      {
        img: '/assets/apartments/1416/8.jpg',
        id: '1416-7',
      },
    ],
    summerPrice: '12 000',
    winterPrice: '6 000',
    rooms: '3',
    floor: '14',
    meta: {
      title: 'Апартамент 1416',
      description:
        'Забронировать апартамент площадью 60 кв. м., 6 спальных мест, 14 этаж, с видом на море в Сочи',
      keywords: 'Апартамент 1416, Барселона парк, Апартамент Сочи',
    },
    sort: '42',
  },
  {
    name: '1415',
    balcony: false,
    studio: false,
    oneRoom: false,
    twoRoom: false,
    threeRoom: true,
    squareMeters: '60',
    view: true,
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '6',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      {
        img: '/assets/apartments/1415/1.jpg',
        id: '1415-0',
      },
      {
        img: '/assets/apartments/1415/2.jpg',
        id: '1415-1',
      },
      {
        img: '/assets/apartments/1415/3.jpg',
        id: '1415-2',
      },
      {
        img: '/assets/apartments/1415/4.jpg',
        id: '1415-3',
      },
      {
        img: '/assets/apartments/1415/5.jpg',
        id: '1415-4',
      },
      {
        img: '/assets/apartments/1415/6.jpg',
        id: '1415-5',
      },
      {
        img: '/assets/apartments/1415/7.jpg',
        id: '1415-6',
      },
      {
        img: '/assets/apartments/1415/8.jpg',
        id: '1415-7',
      },
    ],
    summerPrice: '12 000',
    winterPrice: '6 000',
    rooms: '3',
    floor: '14',
    meta: {
      title: 'Апартамент 1415',
      description:
        'Забронировать апартамент площадью 60 кв. м., 6 спальных мест, 14 этаж, с видом на море в Сочи',
      keywords: 'Апартамент 1415, Барселона парк, Апартамент Сочи',
    },
    sort: '41',
  },
  {
    name: '1410',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '54',
    view: true,
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: true,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      {
        img: '/assets/apartments/1410/1.jpg',
        id: '1410-0',
      },
      {
        img: '/assets/apartments/1410/2.jpg',
        id: '1410-1',
      },
      {
        img: '/assets/apartments/1410/3.jpg',
        id: '1410-2',
      },
      {
        img: '/assets/apartments/1410/4.jpg',
        id: '1410-3',
      },
      {
        img: '/assets/apartments/1410/5.jpg',
        id: '1410-4',
      },
      {
        img: '/assets/apartments/1410/6.jpg',
        id: '1410-5',
      },
      {
        img: '/assets/apartments/1410/7.jpg',
        id: '1410-6',
      },
      {
        img: '/assets/apartments/1410/8.jpg',
        id: '1410-7',
      },
    ],
    summerPrice: '12 000',
    winterPrice: '6 000',
    rooms: '2',
    floor: '14',
    meta: {
      title: 'Апартамент 1410',
      description:
        'Забронировать апартамент площадью 54 кв. м., 4 спальных места, 14 этаж, с видом на море в Сочи',
      keywords: 'Апартамент 1410, Барселона парк, Апартамент Сочи',
    },
    sort: '40',
  },
  {
    name: '1409',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '50',
    view: true,
    hairDryer: true,
    dishwasher: false,
    oven: true,
    sleepingPlaces: '3',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      {
        img: '/assets/apartments/1409/1.jpg',
        id: '1409-0',
      },
      {
        img: '/assets/apartments/1409/2.jpg',
        id: '1409-1',
      },
      {
        img: '/assets/apartments/1409/3.jpg',
        id: '1409-2',
      },
      {
        img: '/assets/apartments/1409/4.jpg',
        id: '1409-3',
      },
      {
        img: '/assets/apartments/1409/5.jpg',
        id: '1409-4',
      },
      {
        img: '/assets/apartments/1409/6.jpg',
        id: '1409-5',
      },
      {
        img: '/assets/apartments/1409/7.jpg',
        id: '1409-6',
      },
      {
        img: '/assets/apartments/1409/8.jpg',
        id: '1409-7',
      },
    ],
    summerPrice: '12 000',
    winterPrice: '6 000',
    rooms: '2',
    floor: '14',
    meta: {
      title: 'Апартамент 1409',
      description:
        'Забронировать апартамент площадью 50 кв. м., 3 спальных места, 14 этаж, с видом на море в Сочи',
      keywords: 'Апартамент 1409, Барселона парк, Апартамент Сочи',
    },
    sort: '39',
  },
  {
    name: '1404',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '50',
    view: true,
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      {
        img: '/assets/apartments/1404/1.jpg',
        id: '1404-0',
      },
      {
        img: '/assets/apartments/1404/2.jpg',
        id: '1404-1',
      },
      {
        img: '/assets/apartments/1404/3.jpg',
        id: '1404-2',
      },
      {
        img: '/assets/apartments/1404/4.jpg',
        id: '1404-3',
      },
      {
        img: '/assets/apartments/1404/5.jpg',
        id: '1404-4',
      },
      {
        img: '/assets/apartments/1404/6.jpg',
        id: '1404-5',
      },
      {
        img: '/assets/apartments/1404/7.jpg',
        id: '1404-6',
      },
      {
        img: '/assets/apartments/1404/8.jpg',
        id: '1404-7',
      },
    ],
    summerPrice: '15 000',
    winterPrice: '6 000',
    rooms: '2',
    floor: '14',
    meta: {
      title: 'Апартамент 1404',
      description:
        'Забронировать апартамент площадью 50 кв. м., 4 спальных места, 14 этаж, с видом на море в Сочи',
      keywords: 'Апартамент 1404, Барселона парк, Апартамент Сочи',
    },
    sort: '38',
  },
  {
    name: '1313',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: false,
    threeRoom: true,
    squareMeters: '58',
    view: true,
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '6',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      {
        img: '/assets/apartments/1313/1.jpg',
        id: '1313-0',
      },
      {
        img: '/assets/apartments/1313/2.jpg',
        id: '1313-1',
      },
      {
        img: '/assets/apartments/1313/3.jpg',
        id: '1313-2',
      },
      {
        img: '/assets/apartments/1313/4.jpg',
        id: '1313-3',
      },
      {
        img: '/assets/apartments/1313/5.jpg',
        id: '1313-4',
      },
      {
        img: '/assets/apartments/1313/6.jpg',
        id: '1313-5',
      },
      {
        img: '/assets/apartments/1313/7.jpg',
        id: '1313-6',
      },
      {
        img: '/assets/apartments/1313/8.jpg',
        id: '1313-7',
      },
    ],
    summerPrice: '12 500',
    winterPrice: '7 000',
    rooms: '3',
    floor: '13',
    meta: {
      title: 'Апартамент 1313',
      description:
        'Забронировать апартамент площадью 58 кв. м., 6 спальных мест, 13 этаж, с видом на море в Сочи',
      keywords: 'Апартамент 1313, Барселона парк, Апартамент Сочи',
    },
    sort: '37',
  },
  {
    name: '1305',
    balcony: false,
    studio: false,
    oneRoom: false,
    twoRoom: false,
    threeRoom: true,
    squareMeters: '59',
    view: false,
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '6',
    wifi: true,
    coffeeMachine: true,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      {
        img: '/assets/apartments/1304 - 1305/1.jpg',
        id: '1305-0',
      },
      {
        img: '/assets/apartments/1304 - 1305/2.jpg',
        id: '1305-1',
      },
      {
        img: '/assets/apartments/1304 - 1305/3.jpg',
        id: '1305-2',
      },
      {
        img: '/assets/apartments/1304 - 1305/4.jpg',
        id: '1305-3',
      },
      {
        img: '/assets/apartments/1304 - 1305/5.jpg',
        id: '1305-4',
      },
      {
        img: '/assets/apartments/1304 - 1305/6.jpg',
        id: '1305-5',
      },
      {
        img: '/assets/apartments/1304 - 1305/7.jpg',
        id: '1305-6',
      },
      {
        img: '/assets/apartments/1304 - 1305/8.jpg',
        id: '1305-7',
      },
    ],
    summerPrice: '12 000',
    winterPrice: '6 000',
    rooms: '3',
    floor: '13',
    meta: {
      title: 'Апартамент 1305',
      description:
        'Забронировать апартамент площадью 59 кв. м., 6 спальных мест, 13 этаж, с видом на город в Сочи',
      keywords: 'Апартамент 1305, Барселона парк, Апартамент Сочи',
    },
    sort: '36',
  },
  {
    name: '1304',
    balcony: false,
    studio: false,
    oneRoom: false,
    twoRoom: false,
    threeRoom: true,
    squareMeters: '59',
    view: false,
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '1',
    wifi: true,
    coffeeMachine: true,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      {
        img: '/assets/apartments/1304 - 1305/1.jpg',
        id: '1304-0',
      },
      {
        img: '/assets/apartments/1304 - 1305/2.jpg',
        id: '1304-1',
      },
      {
        img: '/assets/apartments/1304 - 1305/3.jpg',
        id: '1304-2',
      },
      {
        img: '/assets/apartments/1304 - 1305/4.jpg',
        id: '1304-3',
      },
      {
        img: '/assets/apartments/1304 - 1305/5.jpg',
        id: '1304-4',
      },
      {
        img: '/assets/apartments/1304 - 1305/6.jpg',
        id: '1304-5',
      },
      {
        img: '/assets/apartments/1304 - 1305/7.jpg',
        id: '1304-6',
      },
      {
        img: '/assets/apartments/1304 - 1305/8.jpg',
        id: '1304-7',
      },
    ],
    summerPrice: '12 000',
    winterPrice: '6 000',
    rooms: '3',
    floor: '13',
    meta: {
      title: 'Апартамент 1304',
      description:
        'Забронировать апартамент площадью 58 кв. м., 6 спальных мест, 13 этаж, с видом на город в Сочи',
      keywords: 'Апартамент 1304, Барселона парк, Апартамент Сочи',
    },
    sort: '35',
  },
  {
    name: '1303',
    balcony: true,
    studio: true,
    oneRoom: false,
    twoRoom: false,
    threeRoom: false,
    squareMeters: '52',
    view: true,
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: true,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      {
        img: '/assets/apartments/1303/1.jpg',
        id: '1303-0',
      },
      {
        img: '/assets/apartments/1303/2.jpg',
        id: '1303-1',
      },
      {
        img: '/assets/apartments/1303/3.jpg',
        id: '1303-2',
      },
      {
        img: '/assets/apartments/1303/4.jpg',
        id: '1303-3',
      },
      {
        img: '/assets/apartments/1303/5.jpg',
        id: '1303-4',
      },
      {
        img: '/assets/apartments/1303/6.jpg',
        id: '1303-5',
      },
      {
        img: '/assets/apartments/1303/7.jpg',
        id: '1303-6',
      },
      {
        img: '/assets/apartments/1303/8.jpg',
        id: '1303-7',
      },
    ],
    summerPrice: '12 000',
    winterPrice: '6 000',
    rooms: 'Студия',
    floor: '13',
    meta: {
      title: 'Апартамент 1303',
      description:
        'Забронировать апартамент площадью 52 кв. м., 4 спальных места, 13 этаж, с видом на море в Сочи',
      keywords: 'Апартамент 1303, Барселона парк, Апартамент Сочи',
    },
    sort: '34',
  },
  {
    name: '1208',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '57',
    view: true,
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      {
        img: '/assets/apartments/1208/1.jpg',
        id: '1208-0',
      },
      {
        img: '/assets/apartments/1208/2.jpg',
        id: '1208-1',
      },
      {
        img: '/assets/apartments/1208/3.jpg',
        id: '1208-2',
      },
      {
        img: '/assets/apartments/1208/4.jpg',
        id: '1208-3',
      },
      {
        img: '/assets/apartments/1208/5.jpg',
        id: '1208-4',
      },
      {
        img: '/assets/apartments/1208/6.jpg',
        id: '1208-5',
      },
      {
        img: '/assets/apartments/1208/7.jpg',
        id: '1208-6',
      },
      {
        img: '/assets/apartments/1208/8.jpg',
        id: '1208-7',
      },
    ],
    summerPrice: '12 000',
    winterPrice: '7 000',
    rooms: '2',
    floor: '12',
    meta: {
      title: 'Апартамент 1208',
      description:
        'Забронировать апартамент площадью 57 кв. м., 4 спальных места, 12 этаж, с видом на море в Сочи',
      keywords: 'Апартамент 1208, Барселона парк, Апартамент Сочи',
    },
    sort: '33',
  },]
