export const withBalcony = [
  {
    name: '1410',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '54',
    view: 'Море',
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: true,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [],
    summerPrice: '15 000',
    winterPrice: '12 000',
    description: '',
  },
  {
    name: '1409',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '50',
    view: 'Море',
    hairDryer: true,
    dishwasher: false,
    oven: true,
    sleepingPlaces: '3',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [],
    summerPrice: '15 000',
    winterPrice: '12 000',
    description: '',
  },
  {
    name: '1404',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '50',
    view: 'Море',
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [],
    summerPrice: '15 000',
    winterPrice: '12 000',
    description: '',
  },
  {
    name: '1313',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: false,
    threeRoom: true,
    squareMeters: '58',
    view: 'Море',
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '6',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [],
    summerPrice: '15 000',
    winterPrice: '12 000',
    description: '',
  },
  {
    name: '1303',
    balcony: true,
    studio: true,
    oneRoom: false,
    twoRoom: false,
    threeRoom: false,
    squareMeters: '52',
    view: 'Море',
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: true,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [],
    summerPrice: '15 000',
    winterPrice: '12 000',
    description: '',
  },
  {
    name: '1208',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '57',
    view: 'Море',
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [],
    summerPrice: '15 000',
    winterPrice: '12 000',
    description: '',
  },
  {
    name: '1207',
    balcony: true,
    studio: true,
    oneRoom: false,
    twoRoom: false,
    threeRoom: false,
    squareMeters: '57',
    view: 'Море',
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [],
    summerPrice: '15 000',
    winterPrice: '12 000',
    description: '',
  },
  {
    name: '1206',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '57',
    view: 'Море',
    hairDryer: true,
    dishwasher: true,
    oven: false,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [],
    summerPrice: '15 000',
    winterPrice: '12 000',
    description: '',
  },
  {
    name: '1111',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '58',
    view: 'Море',
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [],
    summerPrice: '15 000',
    winterPrice: '12 000',
    description: '',
  },
  {
    name: '1110',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: false,
    threeRoom: true,
    squareMeters: '57',
    view: 'Море',
    hairDryer: true,
    dishwasher: true,
    oven: false,
    sleepingPlaces: '6',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [],
    summerPrice: '15 000',
    winterPrice: '12 000',
    description: '',
  },
  {
    name: '1105',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '57',
    view: 'Море',
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '6',
    wifi: true,
    coffeeMachine: true,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [],
    summerPrice: '15 000',
    winterPrice: '12 000',
    description: '',
  },
  {
    name: '1104',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '57',
    view: 'Море',
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '6',
    wifi: true,
    coffeeMachine: true,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [],
    summerPrice: '15 000',
    winterPrice: '12 000',
    description: '',
  },
  {
    name: '1103',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '57',
    view: 'Море',
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '5',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [],
    summerPrice: '15 000',
    winterPrice: '12 000',
    description: '',
  },
  {
    name: '1014',
    balcony: true,
    studio: false,
    oneRoom: true,
    twoRoom: false,
    threeRoom: false,
    squareMeters: '58',
    view: 'Море',
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '5',
    wifi: true,
    coffeeMachine: true,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [],
    summerPrice: '15 000',
    winterPrice: '12 000',
    description: '',
  },
  {
    name: '1013',
    balcony: true,
    studio: false,
    oneRoom: true,
    twoRoom: false,
    threeRoom: false,
    squareMeters: '58',
    view: 'Море',
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '5',
    wifi: true,
    coffeeMachine: true,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [],
    summerPrice: '15 000',
    winterPrice: '12 000',
    description: '',
  },
  {
    name: '1003',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '57',
    view: 'Море',
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [],
    summerPrice: '15 000',
    winterPrice: '12 000',
    description: '',
  },
  {
    name: '907',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '57',
    view: 'Море',
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [],
    summerPrice: '15 000',
    winterPrice: '12 000',
    description: '',
  },
  {
    name: '805',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '57',
    view: 'Море',
    hairDryer: true,
    dishwasher: true,
    oven: false,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [],
    summerPrice: '15 000',
    winterPrice: '12 000',
    description: '',
  },
  {
    name: '716',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '57',
    view: 'Море',
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [],
    summerPrice: '15 000',
    winterPrice: '12 000',
    description: '',
  },
  {
    name: '712',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '57',
    view: 'Море',
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [],
    summerPrice: '15 000',
    winterPrice: '12 000',
    description: '',
  },
  {
    name: '709',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '54',
    view: 'Море',
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [],
    summerPrice: '15 000',
    winterPrice: '12 000',
    description: '',
  },
  {
    name: '705',
    balcony: true,
    studio: true,
    oneRoom: false,
    twoRoom: false,
    threeRoom: false,
    squareMeters: '53',
    view: 'Море',
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [],
    summerPrice: '15 000',
    winterPrice: '12 000',
    description: '',
  },
  {
    name: '613',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '55',
    view: 'Город',
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: true,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [],
    summerPrice: '15 000',
    winterPrice: '12 000',
    description: '',
  },
  {
    name: '612',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '55',
    view: 'Город',
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '5',
    wifi: true,
    coffeeMachine: true,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [],
    summerPrice: '15 000',
    winterPrice: '12 000',
    description: '',
  },
  {
    name: '607',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '53',
    view: 'Город',
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: true,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [],
    summerPrice: '15 000',
    winterPrice: '12 000',
    description: '',
  },
  {
    name: '606',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '53',
    view: 'Город',
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [],
    summerPrice: '15 000',
    winterPrice: '12 000',
    description: '',
  },
  {
    name: '605',
    balcony: true,
    studio: true,
    oneRoom: false,
    twoRoom: false,
    threeRoom: false,
    squareMeters: '50',
    view: 'Город',
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [],
    summerPrice: '15 000',
    winterPrice: '12 000',
    description: '',
  },
  {
    name: '509',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '57',
    view: 'Город',
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '5',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [],
    summerPrice: '15 000',
    winterPrice: '12 000',
    description: '',
  },
  {
    name: '503',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '52',
    view: 'Город',
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [],
    summerPrice: '15 000',
    winterPrice: '12 000',
    description: '',
  },
  {
    name: '416',
    balcony: true,
    studio: false,
    oneRoom: true,
    twoRoom: false,
    threeRoom: false,
    squareMeters: '45',
    view: 'Город',
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [],
    summerPrice: '15 000',
    winterPrice: '12 000',
    description: '',
  },
  {
    name: '402',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: false,
    threeRoom: true,
    squareMeters: '57',
    view: 'Город',
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '6',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [],
    summerPrice: '15 000',
    winterPrice: '12 000',
    description: '',
  },
  {
    name: '312',
    balcony: true,
    studio: false,
    oneRoom: true,
    twoRoom: false,
    threeRoom: false,
    squareMeters: '45',
    view: 'Город',
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [],
    summerPrice: '15 000',
    winterPrice: '12 000',
    description: '',
  },
];
