export const table = [
  {
    name: '1416',
    balcony: false,
    studio: false,
    oneRoom: false,
    twoRoom: false,
    threeRoom: true,
    squareMeters: '60',
    view: true,
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '6',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartment 2-16/1.jpg',
      '/assets/apartment 2-16/2.jpg',
      '/assets/apartment 2-16/3.jpg',
      '/assets/apartment 2-16/4.jpg',
      '/assets/apartment 2-16/5.jpg',
      '/assets/apartment 2-16/6.jpg',
      '/assets/apartment 2-16/7.jpg',
      '/assets/apartment 2-16/8.jpg',
    ],
    summerPrice: '12 000',
    winterPrice: '6 000',
    rooms: '3',
    floor: '14',
    description: '',
    sort: '42',
  },
  {
    name: '1415',
    balcony: false,
    studio: false,
    oneRoom: false,
    twoRoom: false,
    threeRoom: true,
    squareMeters: '60',
    view: true,
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '6',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartment 2-16/1.jpg',
      '/assets/apartment 2-16/2.jpg',
      '/assets/apartment 2-16/3.jpg',
      '/assets/apartment 2-16/4.jpg',
      '/assets/apartment 2-16/5.jpg',
      '/assets/apartment 2-16/6.jpg',
      '/assets/apartment 2-16/7.jpg',
      '/assets/apartment 2-16/8.jpg',
    ],
    summerPrice: '12 000',
    winterPrice: '6 000',
    rooms: '3',
    floor: '14',
    description: '',
    sort: '41',
  },
  {
    name: '1410',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '54',
    view: true,
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: true,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartment 2-16/1.jpg',
      '/assets/apartment 2-16/2.jpg',
      '/assets/apartment 2-16/3.jpg',
      '/assets/apartment 2-16/4.jpg',
      '/assets/apartment 2-16/5.jpg',
      '/assets/apartment 2-16/6.jpg',
      '/assets/apartment 2-16/7.jpg',
      '/assets/apartment 2-16/8.jpg',
    ],
    summerPrice: '12 000',
    winterPrice: '6 000',
    rooms: '2',
    floor: '14',
    description: '',
    sort: '40',
  },
  {
    name: '1409',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '50',
    view: true,
    hairDryer: true,
    dishwasher: false,
    oven: true,
    sleepingPlaces: '3',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartment 2-16/1.jpg',
      '/assets/apartment 2-16/2.jpg',
      '/assets/apartment 2-16/3.jpg',
      '/assets/apartment 2-16/4.jpg',
      '/assets/apartment 2-16/5.jpg',
      '/assets/apartment 2-16/6.jpg',
      '/assets/apartment 2-16/7.jpg',
      '/assets/apartment 2-16/8.jpg',
    ],
    summerPrice: '12 000',
    winterPrice: '6 000',
    rooms: '2',
    floor: '14',
    description: '',
    sort: '39',
  },
  {
    name: '1404',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '50',
    view: true,
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartment 2-16/1.jpg',
      '/assets/apartment 2-16/2.jpg',
      '/assets/apartment 2-16/3.jpg',
      '/assets/apartment 2-16/4.jpg',
      '/assets/apartment 2-16/5.jpg',
      '/assets/apartment 2-16/6.jpg',
      '/assets/apartment 2-16/7.jpg',
      '/assets/apartment 2-16/8.jpg',
    ],
    summerPrice: '15 000',
    winterPrice: '6 000',
    rooms: '2',
    floor: '14',
    description: '',
    sort: '38',
  },
  {
    name: '1313',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: false,
    threeRoom: true,
    squareMeters: '58',
    view: true,
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '6',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartment 2-16/1.jpg',
      '/assets/apartment 2-16/2.jpg',
      '/assets/apartment 2-16/3.jpg',
      '/assets/apartment 2-16/4.jpg',
      '/assets/apartment 2-16/5.jpg',
      '/assets/apartment 2-16/6.jpg',
      '/assets/apartment 2-16/7.jpg',
      '/assets/apartment 2-16/8.jpg',
    ],
    summerPrice: '12 500',
    winterPrice: '7 000',
    rooms: '3',
    floor: '13',
    description: '',
    sort: '37',
  },
  {
    name: '1305',
    balcony: false,
    studio: false,
    oneRoom: false,
    twoRoom: false,
    threeRoom: true,
    squareMeters: '59',
    view: false,
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '1',
    wifi: true,
    coffeeMachine: true,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartment 2-16/1.jpg',
      '/assets/apartment 2-16/2.jpg',
      '/assets/apartment 2-16/3.jpg',
      '/assets/apartment 2-16/4.jpg',
      '/assets/apartment 2-16/5.jpg',
      '/assets/apartment 2-16/6.jpg',
      '/assets/apartment 2-16/7.jpg',
      '/assets/apartment 2-16/8.jpg',
    ],
    summerPrice: '12 000',
    winterPrice: '6 000',
    rooms: '3',
    floor: '13',
    description: '',
    sort: '36',
  },
  {
    name: '1304',
    balcony: false,
    studio: false,
    oneRoom: false,
    twoRoom: false,
    threeRoom: true,
    squareMeters: '59',
    view: false,
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '1',
    wifi: true,
    coffeeMachine: true,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartment 2-16/1.jpg',
      '/assets/apartment 2-16/2.jpg',
      '/assets/apartment 2-16/3.jpg',
      '/assets/apartment 2-16/4.jpg',
      '/assets/apartment 2-16/5.jpg',
      '/assets/apartment 2-16/6.jpg',
      '/assets/apartment 2-16/7.jpg',
      '/assets/apartment 2-16/8.jpg',
    ],
    summerPrice: '12 000',
    winterPrice: '6 000',
    rooms: '3',
    floor: '13',
    description: '',
    sort: '35',
  },
  {
    name: '1303',
    balcony: true,
    studio: true,
    oneRoom: false,
    twoRoom: false,
    threeRoom: false,
    squareMeters: '52',
    view: true,
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: true,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartment 2-16/1.jpg',
      '/assets/apartment 2-16/2.jpg',
      '/assets/apartment 2-16/3.jpg',
      '/assets/apartment 2-16/4.jpg',
      '/assets/apartment 2-16/5.jpg',
      '/assets/apartment 2-16/6.jpg',
      '/assets/apartment 2-16/7.jpg',
      '/assets/apartment 2-16/8.jpg',
    ],
    summerPrice: '12 000',
    winterPrice: '6 000',
    rooms: 'Студия',
    floor: '13',
    description: '',
    sort: '34',
  },
  {
    name: '1208',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '57',
    view: true,
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartment 2-16/1.jpg',
      '/assets/apartment 2-16/2.jpg',
      '/assets/apartment 2-16/3.jpg',
      '/assets/apartment 2-16/4.jpg',
      '/assets/apartment 2-16/5.jpg',
      '/assets/apartment 2-16/6.jpg',
      '/assets/apartment 2-16/7.jpg',
      '/assets/apartment 2-16/8.jpg',
    ],
    summerPrice: '12 000',
    winterPrice: '7 000',
    rooms: '2',
    floor: '12',
    description: '',
    sort: '33',
  },
  {
    name: '1207',
    balcony: true,
    studio: true,
    oneRoom: false,
    twoRoom: false,
    threeRoom: false,
    squareMeters: '57',
    view: true,
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartment 2-16/1.jpg',
      '/assets/apartment 2-16/2.jpg',
      '/assets/apartment 2-16/3.jpg',
      '/assets/apartment 2-16/4.jpg',
      '/assets/apartment 2-16/5.jpg',
      '/assets/apartment 2-16/6.jpg',
      '/assets/apartment 2-16/7.jpg',
      '/assets/apartment 2-16/8.jpg',
    ],
    summerPrice: '10 000',
    winterPrice: '6 000',
    rooms: 'Студия',
    floor: '12',
    description: '',
    sort: '32',
  },
  {
    name: '1206',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '57',
    view: true,
    hairDryer: true,
    dishwasher: true,
    oven: false,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartment 2-16/1.jpg',
      '/assets/apartment 2-16/2.jpg',
      '/assets/apartment 2-16/3.jpg',
      '/assets/apartment 2-16/4.jpg',
      '/assets/apartment 2-16/5.jpg',
      '/assets/apartment 2-16/6.jpg',
      '/assets/apartment 2-16/7.jpg',
      '/assets/apartment 2-16/8.jpg',
    ],
    summerPrice: '11 000',
    winterPrice: '6 000',
    rooms: '2',
    floor: '12',
    description: '',
    sort: '31',
  },
  {
    name: '1111',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '58',
    view: true,
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartment 2-16/1.jpg',
      '/assets/apartment 2-16/2.jpg',
      '/assets/apartment 2-16/3.jpg',
      '/assets/apartment 2-16/4.jpg',
      '/assets/apartment 2-16/5.jpg',
      '/assets/apartment 2-16/6.jpg',
      '/assets/apartment 2-16/7.jpg',
      '/assets/apartment 2-16/8.jpg',
    ],
    summerPrice: '11 000',
    winterPrice: '5 500',
    rooms: '2',
    floor: '11',
    description: '',
    sort: '30',
  },
  {
    name: '1110',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: false,
    threeRoom: true,
    squareMeters: '57',
    view: true,
    hairDryer: true,
    dishwasher: true,
    oven: false,
    sleepingPlaces: '6',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartment 2-16/1.jpg',
      '/assets/apartment 2-16/2.jpg',
      '/assets/apartment 2-16/3.jpg',
      '/assets/apartment 2-16/4.jpg',
      '/assets/apartment 2-16/5.jpg',
      '/assets/apartment 2-16/6.jpg',
      '/assets/apartment 2-16/7.jpg',
      '/assets/apartment 2-16/8.jpg',
    ],
    summerPrice: '12 000',
    winterPrice: '6 000',
    rooms: '3',
    floor: '11',
    description: '',
    sort: '29',
  },
  {
    name: '1109',
    balcony: false,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '56',
    view: true,
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: true,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartment 2-16/1.jpg',
      '/assets/apartment 2-16/2.jpg',
      '/assets/apartment 2-16/3.jpg',
      '/assets/apartment 2-16/4.jpg',
      '/assets/apartment 2-16/5.jpg',
      '/assets/apartment 2-16/6.jpg',
      '/assets/apartment 2-16/7.jpg',
      '/assets/apartment 2-16/8.jpg',
    ],
    summerPrice: '10 000',
    winterPrice: '5 000',
    rooms: '2',
    floor: '11',
    description: '',
    sort: '28',
  },
  {
    name: '1105',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '57',
    view: true,
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '6',
    wifi: true,
    coffeeMachine: true,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartment 2-16/1.jpg',
      '/assets/apartment 2-16/2.jpg',
      '/assets/apartment 2-16/3.jpg',
      '/assets/apartment 2-16/4.jpg',
      '/assets/apartment 2-16/5.jpg',
      '/assets/apartment 2-16/6.jpg',
      '/assets/apartment 2-16/7.jpg',
      '/assets/apartment 2-16/8.jpg',
    ],
    summerPrice: '12 000',
    winterPrice: '6 000',
    rooms: '2',
    floor: '11',
    description: '',
    sort: '27',
  },
  {
    name: '1104',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '57',
    view: true,
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '6',
    wifi: true,
    coffeeMachine: true,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartment 2-16/1.jpg',
      '/assets/apartment 2-16/2.jpg',
      '/assets/apartment 2-16/3.jpg',
      '/assets/apartment 2-16/4.jpg',
      '/assets/apartment 2-16/5.jpg',
      '/assets/apartment 2-16/6.jpg',
      '/assets/apartment 2-16/7.jpg',
      '/assets/apartment 2-16/8.jpg',
    ],
    summerPrice: '12 000',
    winterPrice: '6 000',
    rooms: '2',
    floor: '11',
    description: '',
    sort: '26',
  },
  {
    name: '1103',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '57',
    view: true,
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '5',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartment 2-16/1.jpg',
      '/assets/apartment 2-16/2.jpg',
      '/assets/apartment 2-16/3.jpg',
      '/assets/apartment 2-16/4.jpg',
      '/assets/apartment 2-16/5.jpg',
      '/assets/apartment 2-16/6.jpg',
      '/assets/apartment 2-16/7.jpg',
      '/assets/apartment 2-16/8.jpg',
    ],
    summerPrice: '10 000',
    winterPrice: '5 000',
    rooms: '2',
    floor: '11',
    description: '',
    sort: '25',
  },
  {
    name: '1014',
    balcony: true,
    studio: false,
    oneRoom: true,
    twoRoom: false,
    threeRoom: false,
    squareMeters: '58',
    view: true,
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '5',
    wifi: true,
    coffeeMachine: true,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartment 2-16/1.jpg',
      '/assets/apartment 2-16/2.jpg',
      '/assets/apartment 2-16/3.jpg',
      '/assets/apartment 2-16/4.jpg',
      '/assets/apartment 2-16/5.jpg',
      '/assets/apartment 2-16/6.jpg',
      '/assets/apartment 2-16/7.jpg',
      '/assets/apartment 2-16/8.jpg',
    ],
    summerPrice: '12 000',
    winterPrice: '7 000',
    rooms: '1',
    floor: '10',
    description: '',
    sort: '24',
  },
  {
    name: '1013',
    balcony: true,
    studio: false,
    oneRoom: true,
    twoRoom: false,
    threeRoom: false,
    squareMeters: '58',
    view: true,
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '5',
    wifi: true,
    coffeeMachine: true,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartment 2-16/1.jpg',
      '/assets/apartment 2-16/2.jpg',
      '/assets/apartment 2-16/3.jpg',
      '/assets/apartment 2-16/4.jpg',
      '/assets/apartment 2-16/5.jpg',
      '/assets/apartment 2-16/6.jpg',
      '/assets/apartment 2-16/7.jpg',
      '/assets/apartment 2-16/8.jpg',
    ],
    summerPrice: '12 000',
    winterPrice: '7 000',
    rooms: '1',
    floor: '10',
    description: '',
    sort: '23',
  },
  {
    name: '1003',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '57',
    view: true,
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartment 2-16/1.jpg',
      '/assets/apartment 2-16/2.jpg',
      '/assets/apartment 2-16/3.jpg',
      '/assets/apartment 2-16/4.jpg',
      '/assets/apartment 2-16/5.jpg',
      '/assets/apartment 2-16/6.jpg',
      '/assets/apartment 2-16/7.jpg',
      '/assets/apartment 2-16/8.jpg',
    ],
    summerPrice: '10 000',
    winterPrice: '5 000',
    rooms: '2',
    floor: '10',
    description: '',
    sort: '22',
  },
  {
    name: '907',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '57',
    view: true,
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartment 2-16/1.jpg',
      '/assets/apartment 2-16/2.jpg',
      '/assets/apartment 2-16/3.jpg',
      '/assets/apartment 2-16/4.jpg',
      '/assets/apartment 2-16/5.jpg',
      '/assets/apartment 2-16/6.jpg',
      '/assets/apartment 2-16/7.jpg',
      '/assets/apartment 2-16/8.jpg',
    ],
    summerPrice: '11 000',
    winterPrice: '6 000',
    rooms: '2',
    floor: '9',
    description: '',
    sort: '21',
  },
  {
    name: '805',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '57',
    view: true,
    hairDryer: true,
    dishwasher: true,
    oven: false,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartment 2-16/1.jpg',
      '/assets/apartment 2-16/2.jpg',
      '/assets/apartment 2-16/3.jpg',
      '/assets/apartment 2-16/4.jpg',
      '/assets/apartment 2-16/5.jpg',
      '/assets/apartment 2-16/6.jpg',
      '/assets/apartment 2-16/7.jpg',
      '/assets/apartment 2-16/8.jpg',
    ],
    summerPrice: '10 000',
    winterPrice: '6 000',
    rooms: '2',
    floor: '8',
    description: '',
    sort: '20',
  },
  {
    name: '716',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '57',
    view: true,
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartment 2-16/1.jpg',
      '/assets/apartment 2-16/2.jpg',
      '/assets/apartment 2-16/3.jpg',
      '/assets/apartment 2-16/4.jpg',
      '/assets/apartment 2-16/5.jpg',
      '/assets/apartment 2-16/6.jpg',
      '/assets/apartment 2-16/7.jpg',
      '/assets/apartment 2-16/8.jpg',
    ],
    summerPrice: '10 000',
    winterPrice: '6 500',
    rooms: '2',
    floor: '7',
    description: '',
    sort: '19',
  },
  {
    name: '715',
    balcony: false,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '57',
    view: true,
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartment 2-16/1.jpg',
      '/assets/apartment 2-16/2.jpg',
      '/assets/apartment 2-16/3.jpg',
      '/assets/apartment 2-16/4.jpg',
      '/assets/apartment 2-16/5.jpg',
      '/assets/apartment 2-16/6.jpg',
      '/assets/apartment 2-16/7.jpg',
      '/assets/apartment 2-16/8.jpg',
    ],
    summerPrice: '10 000',
    winterPrice: '6 500',
    rooms: '2',
    floor: '7',
    description: '',
    sort: '18',
  },
  {
    name: '712',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '57',
    view: true,
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartment 2-16/1.jpg',
      '/assets/apartment 2-16/2.jpg',
      '/assets/apartment 2-16/3.jpg',
      '/assets/apartment 2-16/4.jpg',
      '/assets/apartment 2-16/5.jpg',
      '/assets/apartment 2-16/6.jpg',
      '/assets/apartment 2-16/7.jpg',
      '/assets/apartment 2-16/8.jpg',
    ],
    summerPrice: '10 000',
    winterPrice: '6 500',
    rooms: '2',
    floor: '7',
    description: '',
    sort: '17',
  },
  {
    name: '709',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '54',
    view: true,
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartment 2-16/1.jpg',
      '/assets/apartment 2-16/2.jpg',
      '/assets/apartment 2-16/3.jpg',
      '/assets/apartment 2-16/4.jpg',
      '/assets/apartment 2-16/5.jpg',
      '/assets/apartment 2-16/6.jpg',
      '/assets/apartment 2-16/7.jpg',
      '/assets/apartment 2-16/8.jpg',
    ],
    summerPrice: '10 000',
    winterPrice: '6 000',
    rooms: '2',
    floor: '7',
    description: '',
    sort: '16',
  },
  {
    name: '705',
    balcony: true,
    studio: true,
    oneRoom: false,
    twoRoom: false,
    threeRoom: false,
    squareMeters: '53',
    view: true,
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartment 2-16/1.jpg',
      '/assets/apartment 2-16/2.jpg',
      '/assets/apartment 2-16/3.jpg',
      '/assets/apartment 2-16/4.jpg',
      '/assets/apartment 2-16/5.jpg',
      '/assets/apartment 2-16/6.jpg',
      '/assets/apartment 2-16/7.jpg',
      '/assets/apartment 2-16/8.jpg',
    ],
    summerPrice: '9 000',
    winterPrice: '5 000',
    rooms: 'Студия',
    floor: '7',
    description: '',
    sort: '15',
  },
  {
    name: '613',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '55',
    view: false,
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: true,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartment 2-16/1.jpg',
      '/assets/apartment 2-16/2.jpg',
      '/assets/apartment 2-16/3.jpg',
      '/assets/apartment 2-16/4.jpg',
      '/assets/apartment 2-16/5.jpg',
      '/assets/apartment 2-16/6.jpg',
      '/assets/apartment 2-16/7.jpg',
      '/assets/apartment 2-16/8.jpg',
    ],
    summerPrice: '10 000',
    winterPrice: '6 000',
    rooms: '2',
    floor: '6',
    description: '',
    sort: '14',
  },
  {
    name: '612',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '55',
    view: false,
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '5',
    wifi: true,
    coffeeMachine: true,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartment 2-16/1.jpg',
      '/assets/apartment 2-16/2.jpg',
      '/assets/apartment 2-16/3.jpg',
      '/assets/apartment 2-16/4.jpg',
      '/assets/apartment 2-16/5.jpg',
      '/assets/apartment 2-16/6.jpg',
      '/assets/apartment 2-16/7.jpg',
      '/assets/apartment 2-16/8.jpg',
    ],
    summerPrice: '11 000',
    winterPrice: '6 000',
    rooms: '2',
    floor: '6',
    description: '',
    sort: '13',
  },
  {
    name: '607',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '53',
    view: false,
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: true,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartment 2-16/1.jpg',
      '/assets/apartment 2-16/2.jpg',
      '/assets/apartment 2-16/3.jpg',
      '/assets/apartment 2-16/4.jpg',
      '/assets/apartment 2-16/5.jpg',
      '/assets/apartment 2-16/6.jpg',
      '/assets/apartment 2-16/7.jpg',
      '/assets/apartment 2-16/8.jpg',
    ],
    summerPrice: '10 000',
    winterPrice: '6 000',
    rooms: '2',
    floor: '6',
    description: '',
    sort: '12',
  },
  {
    name: '606',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '53',
    view: false,
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartment 2-16/1.jpg',
      '/assets/apartment 2-16/2.jpg',
      '/assets/apartment 2-16/3.jpg',
      '/assets/apartment 2-16/4.jpg',
      '/assets/apartment 2-16/5.jpg',
      '/assets/apartment 2-16/6.jpg',
      '/assets/apartment 2-16/7.jpg',
      '/assets/apartment 2-16/8.jpg',
    ],
    summerPrice: '9 000',
    winterPrice: '5 000',
    rooms: '2',
    floor: '6',
    description: '',
    sort: '11',
  },
  {
    name: '605',
    balcony: true,
    studio: true,
    oneRoom: false,
    twoRoom: false,
    threeRoom: false,
    squareMeters: '50',
    view: false,
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartment 2-16/1.jpg',
      '/assets/apartment 2-16/2.jpg',
      '/assets/apartment 2-16/3.jpg',
      '/assets/apartment 2-16/4.jpg',
      '/assets/apartment 2-16/5.jpg',
      '/assets/apartment 2-16/6.jpg',
      '/assets/apartment 2-16/7.jpg',
      '/assets/apartment 2-16/8.jpg',
    ],
    summerPrice: '8 500',
    winterPrice: '5 000',
    rooms: 'Студия',
    floor: '6',
    description: '',
    sort: '10',
  },
  {
    name: '509',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '57',
    view: false,
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '5',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartment 2-16/1.jpg',
      '/assets/apartment 2-16/2.jpg',
      '/assets/apartment 2-16/3.jpg',
      '/assets/apartment 2-16/4.jpg',
      '/assets/apartment 2-16/5.jpg',
      '/assets/apartment 2-16/6.jpg',
      '/assets/apartment 2-16/7.jpg',
      '/assets/apartment 2-16/8.jpg',
    ],
    summerPrice: '10 000',
    winterPrice: '6 000',
    rooms: '2',
    floor: '5',
    description: '',
    sort: '9',
  },
  {
    name: '503',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '52',
    view: false,
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartment 2-16/1.jpg',
      '/assets/apartment 2-16/2.jpg',
      '/assets/apartment 2-16/3.jpg',
      '/assets/apartment 2-16/4.jpg',
      '/assets/apartment 2-16/5.jpg',
      '/assets/apartment 2-16/6.jpg',
      '/assets/apartment 2-16/7.jpg',
      '/assets/apartment 2-16/8.jpg',
    ],
    summerPrice: '9 000',
    winterPrice: '5 000',
    rooms: '2',
    floor: '5',
    description: '',
    sort: '8',
  },
  {
    name: '416',
    balcony: true,
    studio: false,
    oneRoom: true,
    twoRoom: false,
    threeRoom: false,
    squareMeters: '45',
    view: false,
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartment 2-16/1.jpg',
      '/assets/apartment 2-16/2.jpg',
      '/assets/apartment 2-16/3.jpg',
      '/assets/apartment 2-16/4.jpg',
      '/assets/apartment 2-16/5.jpg',
      '/assets/apartment 2-16/6.jpg',
      '/assets/apartment 2-16/7.jpg',
      '/assets/apartment 2-16/8.jpg',
    ],
    summerPrice: '8 500',
    winterPrice: '5 000',
    rooms: '1',
    floor: '4',
    description: '',
    sort: '7',
  },
  {
    name: '415',
    balcony: false,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '45',
    view: false,
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartment 2-16/1.jpg',
      '/assets/apartment 2-16/2.jpg',
      '/assets/apartment 2-16/3.jpg',
      '/assets/apartment 2-16/4.jpg',
      '/assets/apartment 2-16/5.jpg',
      '/assets/apartment 2-16/6.jpg',
      '/assets/apartment 2-16/7.jpg',
      '/assets/apartment 2-16/8.jpg',
    ],
    summerPrice: '8 000',
    winterPrice: '4 500',
    rooms: '2',
    floor: '4',
    description: '',
    sort: '6',
  },
  {
    name: '402',
    balcony: true,
    studio: false,
    oneRoom: false,
    twoRoom: false,
    threeRoom: true,
    squareMeters: '57',
    view: false,
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '6',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartment 2-16/1.jpg',
      '/assets/apartment 2-16/2.jpg',
      '/assets/apartment 2-16/3.jpg',
      '/assets/apartment 2-16/4.jpg',
      '/assets/apartment 2-16/5.jpg',
      '/assets/apartment 2-16/6.jpg',
      '/assets/apartment 2-16/7.jpg',
      '/assets/apartment 2-16/8.jpg',
    ],
    summerPrice: '10 000',
    winterPrice: '5 000',
    rooms: '3',
    floor: '4',
    description: '',
    sort: '5',
  },
  {
    name: '312',
    balcony: true,
    studio: false,
    oneRoom: true,
    twoRoom: false,
    threeRoom: false,
    squareMeters: '45',
    view: false,
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartment 2-16/1.jpg',
      '/assets/apartment 2-16/2.jpg',
      '/assets/apartment 2-16/3.jpg',
      '/assets/apartment 2-16/4.jpg',
      '/assets/apartment 2-16/5.jpg',
      '/assets/apartment 2-16/6.jpg',
      '/assets/apartment 2-16/7.jpg',
      '/assets/apartment 2-16/8.jpg',
    ],
    summerPrice: '9 000',
    winterPrice: '6 000',
    rooms: '1',
    floor: '3',
    description: '',
    sort: '4',
  },
  {
    name: '310',
    balcony: false,
    studio: false,
    oneRoom: true,
    twoRoom: false,
    threeRoom: false,
    squareMeters: '45',
    view: false,
    hairDryer: true,
    dishwasher: false,
    oven: true,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartment 2-16/1.jpg',
      '/assets/apartment 2-16/2.jpg',
      '/assets/apartment 2-16/3.jpg',
      '/assets/apartment 2-16/4.jpg',
      '/assets/apartment 2-16/5.jpg',
      '/assets/apartment 2-16/6.jpg',
      '/assets/apartment 2-16/7.jpg',
      '/assets/apartment 2-16/8.jpg',
    ],
    summerPrice: '9 000',
    winterPrice: '5 000',
    rooms: '1',
    floor: '3',
    description: '',
    sort: '3',
  },
  {
    name: '21/8',
    balcony: false,
    studio: false,
    oneRoom: false,
    twoRoom: false,
    threeRoom: true,
    squareMeters: '48',
    view: false,
    hairDryer: true,
    dishwasher: false,
    oven: false,
    sleepingPlaces: '6',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartment 2-16/1.jpg',
      '/assets/apartment 2-16/2.jpg',
      '/assets/apartment 2-16/3.jpg',
      '/assets/apartment 2-16/4.jpg',
      '/assets/apartment 2-16/5.jpg',
      '/assets/apartment 2-16/6.jpg',
      '/assets/apartment 2-16/7.jpg',
      '/assets/apartment 2-16/8.jpg',
    ],
    summerPrice: '10 000',
    winterPrice: '6 000',
    rooms: '3',
    floor: '1',
    description: '',
    sort: '2',
  },
  {
    name: '21/6',
    balcony: false,
    studio: false,
    oneRoom: false,
    twoRoom: true,
    threeRoom: false,
    squareMeters: '48',
    view: false,
    hairDryer: true,
    dishwasher: true,
    oven: true,
    sleepingPlaces: '4',
    wifi: true,
    coffeeMachine: false,
    towels: true,
    iron: true,
    conditioner: true,
    washer: true,
    microwave: true,
    pictures: [
      '/assets/apartment 2-16/1.jpg',
      '/assets/apartment 2-16/2.jpg',
      '/assets/apartment 2-16/3.jpg',
      '/assets/apartment 2-16/4.jpg',
      '/assets/apartment 2-16/5.jpg',
      '/assets/apartment 2-16/6.jpg',
      '/assets/apartment 2-16/7.jpg',
      '/assets/apartment 2-16/8.jpg',
    ],
    summerPrice: '10 000',
    winterPrice: '6 000',
    rooms: '2',
    floor: '1',
    description: '',
    sort: '1',
  },
];
