export const categories = [
  {
    name: "Все апартаменты",
    src: "/assets/categories images/AllApartments.webp",
    alt: "Категория - Все апартаменты",
    link: "/Category/All-apartments",
  },
  {
    name: "С балконом",
    src: "/assets/categories images/withBalcony.webp",
    alt: "Категория - с балконом",
    link: "/Category/With-balcony",
  },
  {
    name: "Без балкона",
    src: "/assets/categories images/withoutBalcony.webp",
    alt: "Категория - без балкона",
    link: "/Category/Without-balcony",
  },
  {
    name: "Студии",
    src: "/assets/categories images/studio.webp",
    alt: "Категория - студии",
    link: "/Category/Studio",
  },
  {
    name: "Однокомнатные",
    src: "/assets/categories images/oneRoom.webp",
    alt: "Категория - однокомнатные",
    link: "/Category/One-room",
  },
  {
    name: "Двухкомнатные",
    src: "/assets/categories images/twoRooms.webp",
    alt: "Категория - двухкомнатные",
    link: "/Category/Two-room",
  },
  {
    name: "Трехкомнатные",
    src: "/assets/categories images/threeRooms.webp",
    alt: "Категория - трехкомнатные",
    link: "/Category/Three-room",
  },
  {
    name: "Вид на море",
    src: "/assets/categories images/sea.webp",
    alt: "Категория - вид на море",
    link: "/Category/Sea-view",
  },
  {
    name: "Вид на город",
    src: "/assets/categories images/city.webp",
    alt: "Категория - вид на город",
    link: "/Category/City-view",
  },
  {
    name: "3 cпальных места",
    src: "/assets/categories images/3Beds.webp",
    alt: "Категория - 3 cпальных места",
    link: "/Category/3-sleeping-places",
  },
  {
    name: "4 cпальных места",
    src: "/assets/categories images/4Beds.webp",
    alt: "Категория - 4 cпальных места",
    link: "/Category/4-sleeping-places",
  },
  {
    name: "5 cпальных мест",
    src: "/assets/categories images/5Beds.webp",
    alt: "Категория - 5 cпальных мест",
    link: "/Category/5-sleeping-places",
  },
  {
    name: "6 cпальных мест",
    src: "/assets/categories images/6Beds.webp",
    alt: "Категория - 6 cпальных мест",
    link: "/Category/6-sleeping-places",
  },
  {
    name: "С кофемашиной",
    src: "/assets/categories images/coffeeMachine.webp",
    alt: "Категория - с кофемашиной",
    link: "/Category/With-coffee-machine",
  },
  {
    name: "С духовкой",
    src: "/assets/categories images/oven.webp",
    alt: "Категория - с духовкой",
    link: "/Category/With-oven",
  },
  {
    name: "С посудомоечной машиной",
    src: "/assets/categories images/dishwasher.webp",
    alt: "Категория - с посудомоечной машиной",
    link: "/Category/With-dishwasher",
  },
  {
    name: "С духовкой и посудомоечной машиной",
    src: "/assets/categories images/ovenAndDishwasher.webp",
    alt: "Категория - с духовкой и посудомоечной машиной",
    link: "/Category/With-oven-and-dishwasher",
  },
];
